//! One-time migrations of legacy config into the workflow model.
//!
//! [`migrate_to_workflows`] (Workflow P1) rewrites the legacy hotkey + mode
//! fields of an [`AppConfig`] into overlay [`WorkflowDef`]s / [`WidgetDef`]s in
//! `config.workflows` / `config.widgets`, then clears the legacy *note* and
//! *listen* hotkey fields (only macOS ever read them, and Task 10 deleted those
//! dispatch arms). The *dictation* hotkey fields are deliberately KEPT: Linux's
//! global-shortcut registration still reads `config.hotkey_dictation` /
//! `hotkey_dictation_toggle` directly (not `effective_workflows`), so clearing
//! them would leave Linux with no dictation shortcut post-migration; macOS
//! ignores them (`build_hotkey_configs` iterates `effective_workflows`). It is
//! idempotent: guarded by `config.workflow_migration_done` and a no-op
//! (returning `false`) once that flag is set.
//!
//! [`migrate_settings_into_flow`] (Workflow P2) later seeds three
//! formerly-global settings — STT language, insert strategy, translate target
//! — onto widget props, guarded by the separate
//! `config.settings_inflow_migration_done` sentinel. It runs after
//! `migrate_to_workflows` (see `main.rs`) so it can operate on the
//! now-workflow-shaped config.
//!
//! [`migrate_hotkeys_to_triggers`] (Workbench P1) runs LAST in the chain,
//! after [`remap_renamed_builtins`]: it converts each workflow's legacy
//! `hotkey` string into a `Trigger::Hotkey` chip and backfills a `PillSlot`
//! chip for any microphone-sourced workflow that lacks one (an overlaid
//! builtin that replaced the seeded copy wholesale). Guarded by the separate
//! `config.triggers_migration_done` sentinel. `save_workflow` (desktop) runs
//! the same hotkey→trigger fold as an ongoing normalization bridge for
//! post-migration saves.

use std::collections::BTreeMap;

use crate::config::AppConfig;
use crate::modes::{Mode, OutputTarget};
use crate::workflow::llm_step::LlmProps;
use crate::workflow::model::{Trigger, WidgetDef, WidgetRole, WorkflowDef};

/// Built-in mode ids that already ship as `llm.*` processor widgets and so are
/// never regenerated by rule 1. (`listen` also has a built-in widget but is
/// deliberately *not* skipped here — a user who customized their "listen" mode
/// should override `llm.listen`; see [`mode_resolves_to_llm_widget`].)
const BUILTIN_LLM_MODE_IDS: [&str; 4] = ["polish", "formal", "translate", "summarize"];

/// Every built-in `llm.*` widget's backing mode id — the set that always
/// resolves to a valid `llm.{id}` widget without migration having to generate it.
const BUILTIN_LLM_WIDGET_IDS: [&str; 5] = ["polish", "formal", "translate", "summarize", "listen"];

/// One-time migration of legacy config into the workflow model.
///
/// Rewrites the legacy dictation / note / listen / text-action hotkey + mode
/// fields of `config` into overlay [`WorkflowDef`]s / [`WidgetDef`]s (pushed
/// into `config.workflows` / `config.widgets`, replacing any built-in of the
/// same id wholesale via [`crate::workflow::engine::effective_workflows`]), then
/// clears the legacy note/listen hotkey fields (the dictation fields are KEPT —
/// Linux still reads them directly; see the module doc). `custom_modes`
/// is the user's `modes.json` map (desktop passes
/// [`crate::modes::load_custom_modes`]; tests pass a hand-built map).
///
/// Idempotent: returns `false` immediately when `config.workflow_migration_done`
/// is already set, and otherwise sets it before returning `true`. A `true`
/// return means the caller should persist `config`.
pub fn migrate_to_workflows(config: &mut AppConfig, custom_modes: &BTreeMap<String, Mode>) -> bool {
    if config.workflow_migration_done {
        return false;
    }

    // ── Rule 1: custom modes with LLM content → `llm.{id}` processor widgets ──
    // The built-in four are skipped (already built-in widgets). STT/model
    // fields are dropped; `vocab_books` is carried over. A content-bearing
    // custom mode referenced ONLY by a listen/text-action is still covered here
    // (this loop iterates every custom mode), and, defensively, by
    // [`ensure_llm_widget`] at the point of reference.
    for (mode_id, mode) in custom_modes {
        if BUILTIN_LLM_MODE_IDS.contains(&mode_id.as_str()) {
            continue;
        }
        if !mode_has_llm_content(mode) {
            continue;
        }
        upsert_widget(config, llm_widget_from_mode(mode_id, mode));
    }

    // ── Rule 2: dictation ──
    // processors = [stt.default] (+ llm.{dictation_mode} when not "raw" and that
    // mode resolves to a real llm widget).
    let mut dictation_processors = vec!["stt.default".to_string()];
    let dictation_mode = config.dictation_mode.clone();
    if dictation_mode != "raw" && mode_resolves_to_llm_widget(&dictation_mode, custom_modes) {
        ensure_llm_widget(config, &dictation_mode, custom_modes);
        dictation_processors.push(format!("llm.{dictation_mode}"));
    }
    let dictation_hotkey = overlay_hotkey(config, "wf.dictation", &config.hotkey_dictation);
    upsert_workflow(
        config,
        WorkflowDef {
            id: "wf.dictation".to_string(),
            name: "听写".to_string(),
            icon: "🎤".to_string(),
            hotkey: dictation_hotkey,
            triggers: Vec::new(),
            source: "src.mic-hold".to_string(),
            processors: dictation_processors.clone(),
            outputs: vec!["out.insert".to_string()],
            builtin: true,
        },
    );
    let dictation_toggle_hotkey = overlay_hotkey(
        config,
        "wf.dictation-toggle",
        &config.hotkey_dictation_toggle,
    );
    if !dictation_toggle_hotkey.is_empty() {
        upsert_workflow(
            config,
            WorkflowDef {
                id: "wf.dictation-toggle".to_string(),
                name: "听写·切换".to_string(),
                icon: "🎤".to_string(),
                hotkey: dictation_toggle_hotkey,
                triggers: Vec::new(),
                source: "src.mic-toggle".to_string(),
                processors: dictation_processors,
                outputs: vec!["out.insert".to_string()],
                builtin: false,
            },
        );
    }

    // ── Rule 3: note (faithful — STT only, no LLM step) ──
    let note_hotkey = overlay_hotkey(config, "wf.note", &config.hotkey_note);
    upsert_workflow(
        config,
        WorkflowDef {
            id: "wf.note".to_string(),
            name: "记笔记".to_string(),
            icon: "📓".to_string(),
            hotkey: note_hotkey,
            triggers: Vec::new(),
            source: "src.mic-hold".to_string(),
            processors: vec!["stt.default".to_string()],
            outputs: vec!["out.quicknote".to_string()],
            builtin: true,
        },
    );
    let notebooks = [
        (1, config.notebook_hotkey_1, config.hotkey_note_1.clone()),
        (2, config.notebook_hotkey_2, config.hotkey_note_2.clone()),
        (3, config.notebook_hotkey_3, config.hotkey_note_3.clone()),
    ];
    for (n, container_id, hotkey) in notebooks {
        if container_id <= 0 {
            continue;
        }
        let wf_id = format!("wf.note-{n}");
        let hotkey = overlay_hotkey(config, &wf_id, &hotkey);
        let widget_id = format!("out.notebook-{container_id}");
        upsert_widget(
            config,
            WidgetDef {
                id: widget_id.clone(),
                role: WidgetRole::Output,
                type_tag: "notebook".to_string(),
                name: format!("笔记本 {container_id}"),
                icon: "📓".to_string(),
                props: serde_json::json!({ "container_id": container_id }),
                builtin: false,
            },
        );
        upsert_workflow(
            config,
            WorkflowDef {
                id: wf_id,
                name: format!("记笔记 {n}"),
                icon: "📓".to_string(),
                hotkey,
                triggers: Vec::new(),
                source: "src.mic-hold".to_string(),
                processors: vec!["stt.default".to_string()],
                outputs: vec![widget_id],
                builtin: false,
            },
        );
    }

    // ── Rule 4: listen (selection → llm.{listen_mode} → speak) ──
    let listen_hotkey = overlay_hotkey(config, "wf.listen", &config.hotkey_listen);
    let listen_mode = config.listen_mode.clone();
    let listen_processors = if listen_mode != "raw"
        && mode_resolves_to_llm_widget(&listen_mode, custom_modes)
    {
        // Content-bearing mode (built-in like `note`, or custom): back the
        // reference with a real widget so it never dangles.
        ensure_llm_widget(config, &listen_mode, custom_modes);
        vec![format!("llm.{listen_mode}")]
    } else {
        // Content-less mode (e.g. `raw`): drop the LLM step rather than dangle a
        // reference to a widget that is never built. Listen then speaks the raw
        // selection — degraded but functional (selection is Text, out.speak
        // accepts Text, so the chain still validates).
        Vec::new()
    };
    upsert_workflow(
        config,
        WorkflowDef {
            id: "wf.listen".to_string(),
            name: "朗读".to_string(),
            icon: "🎧".to_string(),
            hotkey: listen_hotkey,
            triggers: Vec::new(),
            source: "src.selection".to_string(),
            processors: listen_processors,
            outputs: vec!["out.speak".to_string()],
            builtin: true,
        },
    );
    // Overlay out.speak with the listen voice settings.
    upsert_widget(
        config,
        WidgetDef {
            id: "out.speak".to_string(),
            role: WidgetRole::Output,
            type_tag: "speak".to_string(),
            name: "朗读".to_string(),
            icon: "🔊".to_string(),
            props: serde_json::json!({
                "voice_profile": config.listen_voice_profile.clone(),
                "voice": config.listen_voice.clone(),
            }),
            builtin: true,
        },
    );

    // ── Rule 5: text actions → wf.ta-{i}, cleared afterward ──
    // Move the bindings out first so the loop can borrow `config` mutably; this
    // also clears `config.text_actions` (prevents double-registration).
    let text_actions = std::mem::take(&mut config.text_actions);
    for (i, binding) in text_actions.iter().enumerate() {
        let name = format!("文本动作 {}", resolve_mode_name(&binding.mode_id, custom_modes));
        let processors = if mode_resolves_to_llm_widget(&binding.mode_id, custom_modes) {
            // Content-bearing mode: back the reference with a real widget.
            ensure_llm_widget(config, &binding.mode_id, custom_modes);
            vec![format!("llm.{}", binding.mode_id)]
        } else {
            // Content-less mode (e.g. `raw`): drop the LLM step; the text-action
            // echoes the raw selection to its output rather than dangling
            // `llm.raw`. (selection is Text; every output accepts Text.)
            Vec::new()
        };
        upsert_workflow(
            config,
            WorkflowDef {
                id: format!("wf.ta-{i}"),
                name,
                icon: "✨".to_string(),
                hotkey: binding.hotkey.clone(),
                triggers: Vec::new(),
                source: "src.selection".to_string(),
                processors,
                outputs: vec![output_id_for_target(&binding.output_target).to_string()],
                builtin: false,
            },
        );
    }

    // ── Rule 6: clear legacy NOTE / LISTEN hotkey fields (values now live in
    // workflows). Only macOS ever read these, and Task 10 deleted those dispatch
    // arms, so clearing is pure hygiene on macOS and a no-op on Linux (Linux
    // never registered note/listen shortcuts).
    //
    // The DICTATION hotkey fields are intentionally NOT cleared: Linux's
    // global-shortcut registration (main.rs) reads `config.hotkey_dictation` /
    // `hotkey_dictation_toggle` DIRECTLY, not `effective_workflows`, so clearing
    // them would leave Linux with no dictation shortcut post-migration — a
    // regression of a previously-working flow. macOS is unaffected:
    // `build_hotkey_configs` iterates `effective_workflows` and never reads these
    // fields (so they are inert there). Their value is also mirrored into
    // wf.dictation / wf.dictation-toggle for the macOS path.
    //
    // `dictation_mode` is likewise preserved (Task 13 keeps the field).
    config.hotkey_note.clear();
    config.hotkey_note_1.clear();
    config.hotkey_note_2.clear();
    config.hotkey_note_3.clear();
    config.hotkey_listen.clear();

    config.workflow_migration_done = true;
    true
}

/// Does `mode_id` resolve to a real `llm.{mode_id}` processor widget after
/// migration? True for a built-in `llm.*` widget ([`BUILTIN_LLM_WIDGET_IDS`]), a
/// content-bearing custom mode (rule 1 / [`ensure_llm_widget`] generates it), or
/// a content-bearing built-in mode such as `note` ([`ensure_llm_widget`]
/// generates it — `note` ships no `llm.note` widget). Used to decide whether a
/// dictation / listen / text-action pipeline gets an LLM step, so a mode with no
/// widget (e.g. built-in `raw`) never produces a dangling reference.
///
/// A custom mode shadows a built-in of the same id (matching `all_modes()`): if
/// a custom mode exists for `mode_id`, only its content decides — the built-in
/// of the same name is not consulted. This keeps the resolver consistent with
/// [`ensure_llm_widget`], so every reference this permits gets a backing widget.
fn mode_resolves_to_llm_widget(mode_id: &str, custom_modes: &BTreeMap<String, Mode>) -> bool {
    if BUILTIN_LLM_WIDGET_IDS.contains(&mode_id) {
        return true;
    }
    if let Some(mode) = custom_modes.get(mode_id) {
        return mode_has_llm_content(mode);
    }
    crate::modes::built_in_modes()
        .get(mode_id)
        .is_some_and(mode_has_llm_content)
}

/// Whether `mode` carries LLM content — a `system` prompt or a `user_template`
/// — and so warrants an `llm.*` processor widget. Modes without either (e.g.
/// built-in `raw`, or `meeting`) resolve to no widget.
fn mode_has_llm_content(mode: &Mode) -> bool {
    mode.system.is_some() || mode.user_template.is_some()
}

/// Build an `llm.{mode_id}` processor [`WidgetDef`] from `mode`'s LLM fields.
/// Shared by rule 1 (custom modes) and [`ensure_llm_widget`] (built-in
/// content-bearing modes referenced only by a listen/text-action). STT/model
/// fields are dropped; `vocab_books` is carried over.
fn llm_widget_from_mode(mode_id: &str, mode: &Mode) -> WidgetDef {
    let props = LlmProps {
        system: mode.system.clone(),
        user_template: mode.user_template.clone(),
        // Legacy `Mode.model` is a model identifier, not a profile id; there is
        // no faithful mapping, so fall back to the global LLM profile.
        model_profile: String::new(),
        temperature: mode.temperature,
        max_tokens: mode.max_tokens,
        output_language: mode.output_language.clone(),
        vocab_books: mode.vocab_books.clone(),
    };
    let props = serde_json::to_value(&props).unwrap_or_else(|_| serde_json::json!({}));
    WidgetDef {
        id: format!("llm.{mode_id}"),
        role: WidgetRole::Processor,
        type_tag: "llm".to_string(),
        name: mode.name.clone(),
        icon: mode.icon.clone(),
        props,
        builtin: false,
    }
}

/// Guarantee that a `llm.{mode_id}` widget exists to back a reference emitted by
/// rules 2/4/5, so migration never produces a dangling processor id. A no-op
/// unless a widget must be generated. Precondition: only called when
/// [`mode_resolves_to_llm_widget`] returned `true` for `mode_id`, so the
/// content-less cases below are defensive and simply generate nothing.
///
/// - `mode_id` is a built-in `llm.*` widget id ([`BUILTIN_LLM_WIDGET_IDS`]):
///   nothing — the widget already ships.
/// - a `llm.{mode_id}` widget was already generated this run (rule 1, or an
///   earlier rules-2/4/5 reference to the same mode): nothing — dedup.
/// - `mode_id` is a **custom** mode with content: generate its widget (covers a
///   custom mode referenced ONLY by a listen/text-action; rule 1 also generates
///   it, in which case the dedup branch above already fired).
/// - `mode_id` is a **built-in** mode with content (e.g. `note`): generate its
///   widget from [`crate::modes::built_in_modes`] — the case rule 1 never covers
///   (it iterates only custom modes), and the one that used to dangle
///   (`llm.note`).
///
/// A custom mode shadows a built-in of the same id (matching `all_modes()`), so
/// a content-less custom mode is NOT backed by a built-in of the same name.
fn ensure_llm_widget(config: &mut AppConfig, mode_id: &str, custom_modes: &BTreeMap<String, Mode>) {
    if BUILTIN_LLM_WIDGET_IDS.contains(&mode_id) {
        return;
    }
    if config.widgets.iter().any(|w| w.id == format!("llm.{mode_id}")) {
        return;
    }
    if let Some(mode) = custom_modes.get(mode_id) {
        if mode_has_llm_content(mode) {
            upsert_widget(config, llm_widget_from_mode(mode_id, mode));
        }
        return;
    }
    if let Some(mode) = crate::modes::built_in_modes().get(mode_id) {
        if mode_has_llm_content(mode) {
            upsert_widget(config, llm_widget_from_mode(mode_id, mode));
        }
    }
}

/// The display name for `mode_id`: the custom mode's name if present, else the
/// built-in mode's name, else the id itself.
fn resolve_mode_name(mode_id: &str, custom_modes: &BTreeMap<String, Mode>) -> String {
    if let Some(m) = custom_modes.get(mode_id) {
        return m.name.clone();
    }
    if let Some(m) = crate::modes::built_in_modes().get(mode_id) {
        return m.name.clone();
    }
    mode_id.to_string()
}

/// Map a legacy [`OutputTarget`] onto the output-widget id a text-action
/// workflow delivers to.
fn output_id_for_target(target: &OutputTarget) -> &'static str {
    match target {
        OutputTarget::FloatingPopup => "out.panel",
        OutputTarget::ActiveTextField => "out.insert",
        OutputTarget::Clipboard => "out.clipboard",
        OutputTarget::AppendToContainer => "out.quicknote",
        OutputTarget::None => "out.clipboard",
    }
}

/// The hotkey for a workflow overlay being (re)built from a legacy field.
///
/// On a fresh migration, `legacy` is the source of truth. But rule 6 clears
/// the legacy fields once migrated, so if `migrate_to_workflows` were ever
/// invoked again after its `workflow_migration_done` guard was bypassed (a
/// future scenario-apply, partial re-migration, or reset), `legacy` would
/// read back as `""`. Writing that straight through would silently overwrite
/// a real hotkey with an empty one; instead, when `legacy` is empty, reuse
/// whatever hotkey the existing `wf_id` overlay already carries (or `""` if
/// there is no existing overlay, matching first-run behavior).
fn overlay_hotkey(config: &AppConfig, wf_id: &str, legacy: &str) -> String {
    if !legacy.is_empty() {
        return legacy.to_string();
    }
    config
        .workflows
        .iter()
        .find(|w| w.id == wf_id)
        .map(|w| w.hotkey.clone())
        .unwrap_or_default()
}

/// Insert `widget` into `config.widgets`, replacing any existing entry with the
/// same id (idempotent; also dedupes notebook widgets that share a container id).
fn upsert_widget(config: &mut AppConfig, widget: WidgetDef) {
    match config.widgets.iter_mut().find(|w| w.id == widget.id) {
        Some(slot) => *slot = widget,
        None => config.widgets.push(widget),
    }
}

/// Insert `workflow` into `config.workflows`, replacing any existing entry with
/// the same id.
fn upsert_workflow(config: &mut AppConfig, workflow: WorkflowDef) {
    match config.workflows.iter_mut().find(|w| w.id == workflow.id) {
        Some(slot) => *slot = workflow,
        None => config.workflows.push(workflow),
    }
}

/// One-shot (idempotent) relocation of three formerly-global settings onto
/// widget props: STT language, insert strategy, and the translate target
/// (baked into the translate prompt). Custom widgets are patched in place;
/// built-ins get an override only when the user's value differs from the
/// built-in default. Returns `true` if anything changed.
///
/// Idempotent: guarded by `config.settings_inflow_migration_done` and a no-op
/// (returning `false`) once that flag is set. Intended to run once at desktop
/// startup, immediately after [`migrate_to_workflows`] (see `main.rs`).
pub fn migrate_settings_into_flow(config: &mut AppConfig) -> bool {
    if config.settings_inflow_migration_done {
        return false;
    }
    let platform_insert_default = if cfg!(target_os = "linux") { "type" } else { "paste" };

    // Helper: fetch a fresh copy of a built-in widget def by id.
    fn builtin(id: &str) -> Option<WidgetDef> {
        crate::workflow::builtin::built_in_widgets().into_iter().find(|w| w.id == id)
    }
    // Helper: set a string prop on a widget def's json object.
    fn set_prop(w: &mut WidgetDef, key: &str, val: &str) {
        if let Some(obj) = w.props.as_object_mut() {
            obj.insert(key.to_string(), serde_json::Value::String(val.to_string()));
        }
    }

    // (1) STT language — patch custom stt widgets; override builtin if non-"auto".
    for w in config.widgets.iter_mut().filter(|w| w.type_tag == "stt") {
        set_prop(w, "language", &config.stt_language);
    }
    if config.stt_language != "auto" && !config.widgets.iter().any(|w| w.id == "stt.default") {
        if let Some(mut w) = builtin("stt.default") {
            w.builtin = false;
            set_prop(&mut w, "language", &config.stt_language);
            upsert_widget(config, w);
        }
    }

    // (2) Insert strategy — patch custom insert widgets; override builtin if != platform default.
    for w in config.widgets.iter_mut().filter(|w| w.type_tag == "insert") {
        set_prop(w, "strategy", &config.injection_strategy);
    }
    if config.injection_strategy != platform_insert_default
        && !config.widgets.iter().any(|w| w.id == "out.insert")
    {
        if let Some(mut w) = builtin("out.insert") {
            w.builtin = false;
            set_prop(&mut w, "strategy", &config.injection_strategy);
            upsert_widget(config, w);
        }
    }

    // (3) Translate target. Two independent concerns:
    //
    //   a) Any EXISTING custom/overriding llm widget in `config.widgets` that
    //      still carries a literal `{target_lang}` placeholder (pre-P2 custom
    //      widgets, or ones copied from the old llm.translate template) gets
    //      it substituted with the user's real target. This matters because
    //      `LlmProcessor` now always passes `""` for `translate_target` at
    //      runtime (translation is prompt-based post-P2 — see
    //      `crate::llm::process_text`), which would otherwise silently
    //      default any such leftover placeholder to "English", regressing a
    //      non-English target the user had configured.
    //   b) The built-in `llm.translate` widget itself no longer has a
    //      placeholder — Task 2 hardcoded it to "English" — so a non-English
    //      target instead gets an override that bakes the real target into
    //      the "to English." clause of the built-in prompt text.
    let target = config.translate_target.clone();
    for w in config.widgets.iter_mut().filter(|w| w.type_tag == "llm") {
        if let Some(obj) = w.props.as_object_mut() {
            for key in ["system", "user_template"] {
                if let Some(s) = obj.get(key).and_then(|v| v.as_str()) {
                    if s.contains("{target_lang}") {
                        let replaced = s.replace("{target_lang}", &target);
                        obj.insert(key.to_string(), serde_json::Value::String(replaced));
                    }
                }
            }
        }
    }
    // Translate target → bake into the built-in translate prompt for non-default users.
    if target != "English" && !target.is_empty()
        && !config.widgets.iter().any(|w| w.id == "llm.translate")
    {
        if let Some(mut w) = builtin("llm.translate") {
            w.builtin = false;
            if let Some(obj) = w.props.as_object_mut() {
                if let Some(s) = obj.get("user_template").and_then(|v| v.as_str()) {
                    let replaced = s.replace("to English.", &format!("to {target}."));
                    obj.insert("user_template".to_string(), serde_json::Value::String(replaced));
                }
            }
            upsert_widget(config, w);
        }
    }

    config.settings_inflow_migration_done = true;
    true
}

/// Idempotent remap of built-in ids that were renamed after shipping in an
/// earlier build, so configs saved by those builds (carrying the old id) keep
/// working. Unlike the one-time `migrate_*` functions this carries NO sentinel:
/// it is a cheap unconditional scan that becomes a no-op (returns `false`) once
/// no stale ids remain.
///
/// Currently handles a single rename: the dialog output widget
/// `out.dialog-explain` → `out.dialog` (the widget is generic — its props carry
/// no explain-specific config — so "explain" semantics live in `wf.explain`,
/// not in the widget id). Both the `config.widgets` entry and any workflow
/// `outputs` reference are rewritten. If a config already carries an `out.dialog`
/// widget entry, the stale `out.dialog-explain` entry is dropped instead of
/// renamed (avoiding a duplicate id). Returns `true` if anything changed.
pub fn remap_renamed_builtins(config: &mut AppConfig) -> bool {
    /// (old_id, new_id) pairs for built-ins renamed after they shipped.
    const RENAMES: [(&str, &str); 1] = [("out.dialog-explain", "out.dialog")];
    let mut changed = false;

    for (old_id, new_id) in RENAMES {
        // Widgets: rename the stale entry in place — unless a new-id entry
        // already exists, in which case drop the stale one to avoid a duplicate.
        if let Some(pos) = config.widgets.iter().position(|w| w.id == old_id) {
            if config.widgets.iter().any(|w| w.id == new_id) {
                config.widgets.remove(pos);
            } else {
                config.widgets[pos].id = new_id.to_string();
            }
            changed = true;
        }

        // Workflow output references.
        for wf in config.workflows.iter_mut() {
            for out in wf.outputs.iter_mut() {
                if out == old_id {
                    *out = new_id.to_string();
                    changed = true;
                }
            }
        }
    }

    changed
}

/// Workbench P1: convert each overlaid/custom workflow's legacy `hotkey`
/// string into a `Trigger::Hotkey` chip (carrying the source microphone
/// widget's `capture` prop as the chip's capture), and preserve the pill
/// roller's previous "all microphone workflows" behavior by ensuring every
/// microphone-sourced entry in `config.workflows` has a PillSlot chip.
/// Builtins that were never overlaid get their PillSlot from
/// `built_in_workflows()` seeding instead.
///
/// Idempotent: guarded by `config.triggers_migration_done` and a no-op
/// (returning `false`) once that flag is set. Must run LAST in the migration
/// chain (see `main.rs`), after `remap_renamed_builtins`, so it observes the
/// fully-migrated workflow shape.
pub fn migrate_hotkeys_to_triggers(config: &mut AppConfig) -> bool {
    if config.triggers_migration_done {
        return false;
    }
    let widgets = crate::workflow::engine::effective_widgets(config);
    let mic_capture = |source: &str| -> Option<Option<String>> {
        // Some(capture) when source is a microphone widget; None otherwise.
        widgets.iter().find(|w| w.id == source).and_then(|w| {
            (w.type_tag == "microphone").then(|| {
                w.props
                    .get("capture")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string())
            })
        })
    };
    let mut next_order: i64 = 1000; // 排在内建种子(0,10,20…)之后
    for wf in config.workflows.iter_mut() {
        let combo = std::mem::take(&mut wf.hotkey);
        let mic = mic_capture(&wf.source);
        if !combo.is_empty()
            && !wf
                .hotkey_triggers()
                .any(|(_, c, _)| c == combo.as_str())
        {
            wf.triggers.push(Trigger::Hotkey {
                combo,
                capture: mic.clone().flatten(),
            });
        }
        if mic.is_some() && wf.pill_order().is_none() {
            wf.triggers.push(Trigger::PillSlot { order: next_order });
            next_order += 10;
        }
    }
    config.triggers_migration_done = true;
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::TextActionBinding;

    /// A custom mode carrying LLM content (system + user_template).
    fn llm_mode(name: &str) -> Mode {
        Mode {
            name: name.to_string(),
            system: Some(format!("You are {name}.")),
            user_template: Some("do <<<{text}>>>".to_string()),
            ..Default::default()
        }
    }

    // ── Rule: default config produces the expected full shape ───────────────

    #[test]
    fn migrate_default_config_produces_expected_shape() {
        let mut cfg = AppConfig::default();
        let custom = BTreeMap::new();

        let changed = migrate_to_workflows(&mut cfg, &custom);
        assert!(changed, "first migration reports a change");
        assert!(cfg.workflow_migration_done, "migration flag is set");

        // Exactly three workflow overlays for the default config: dictation,
        // note, listen (no toggle, no notebook-N, no text-actions).
        assert_eq!(cfg.workflows.len(), 3, "dictation + note + listen only");
        // Exactly one widget overlay: the out.speak listen-voice override.
        assert_eq!(cfg.widgets.len(), 1, "only the out.speak override");

        // wf.dictation overlay: the dictation hotkey lands here; raw mode ⇒ no
        // LLM step; mic-hold source; insert output; builtin preserved.
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").expect("wf.dictation");
        assert_eq!(d.hotkey, "cmd+shift+space");
        assert_eq!(d.source, "src.mic-hold");
        assert_eq!(d.processors, vec!["stt.default".to_string()]);
        assert_eq!(d.outputs, vec!["out.insert".to_string()]);
        assert!(d.builtin);

        // No toggle workflow: hotkey_dictation_toggle is empty by default.
        assert!(!cfg.workflows.iter().any(|w| w.id == "wf.dictation-toggle"));

        // wf.note overlay: note hotkey; STT only (no LLM — faithful); quicknote.
        let n = cfg.workflows.iter().find(|w| w.id == "wf.note").expect("wf.note");
        assert_eq!(n.hotkey, "option+n");
        assert_eq!(n.source, "src.mic-hold");
        assert_eq!(n.processors, vec!["stt.default".to_string()]);
        assert_eq!(n.outputs, vec!["out.quicknote".to_string()]);
        assert!(n.builtin);

        // No notebook-N workflows: notebook_hotkey_N are all 0 by default.
        assert!(!cfg.workflows.iter().any(|w| w.id.starts_with("wf.note-")));

        // wf.listen overlay: listen hotkey; llm.listen; speak output.
        let l = cfg.workflows.iter().find(|w| w.id == "wf.listen").expect("wf.listen");
        assert_eq!(l.hotkey, "option+l");
        assert_eq!(l.source, "src.selection");
        assert_eq!(l.processors, vec!["llm.listen".to_string()]);
        assert_eq!(l.outputs, vec!["out.speak".to_string()]);
        assert!(l.builtin);

        // out.speak override carries the (default) listen voice settings.
        let sp = cfg.widgets.iter().find(|w| w.id == "out.speak").expect("out.speak override");
        assert_eq!(sp.role, WidgetRole::Output);
        assert_eq!(sp.type_tag, "speak");
        assert_eq!(sp.props["voice_profile"], "");
        assert_eq!(sp.props["voice"], "default");

        // No text actions by default.
        assert!(!cfg.workflows.iter().any(|w| w.id.starts_with("wf.ta-")));
        assert!(cfg.text_actions.is_empty());

        // Rule 6: legacy NOTE/LISTEN hotkey fields are cleared. The DICTATION
        // fields are KEPT — Linux's global-shortcut registration reads them
        // directly, so clearing would break Linux dictation; their value also
        // lives in the generated wf.dictation hotkey. dictation_mode preserved.
        assert_eq!(cfg.hotkey_dictation, "cmd+shift+space", "dictation hotkey KEPT for Linux");
        assert!(
            cfg.hotkey_dictation_toggle.is_empty(),
            "toggle hotkey empty by default (not cleared — it was already empty)"
        );
        assert!(cfg.hotkey_note.is_empty());
        assert!(cfg.hotkey_note_1.is_empty());
        assert!(cfg.hotkey_note_2.is_empty());
        assert!(cfg.hotkey_note_3.is_empty());
        assert!(cfg.hotkey_listen.is_empty());
        assert_eq!(cfg.dictation_mode, "raw");
    }

    // ── Rule: idempotency ───────────────────────────────────────────────────

    #[test]
    fn migrate_is_idempotent() {
        let mut cfg = AppConfig::default();
        let custom = BTreeMap::new();

        assert!(migrate_to_workflows(&mut cfg, &custom), "first call changes config");
        let workflows_after_first = cfg.workflows.clone();
        let widgets_after_first = cfg.widgets.clone();
        let dictation_mode_after_first = cfg.dictation_mode.clone();

        // Second call is a no-op: returns false, mutates nothing.
        assert!(!migrate_to_workflows(&mut cfg, &custom), "second call reports no change");
        assert_eq!(cfg.workflows, workflows_after_first, "workflows unchanged");
        assert_eq!(cfg.widgets, widgets_after_first, "widgets unchanged");
        assert_eq!(cfg.dictation_mode, dictation_mode_after_first);
        assert!(cfg.workflow_migration_done);
    }

    // Guards the `overlay_hotkey` hardening: if `workflow_migration_done` is
    // ever reset without restoring the legacy hotkey fields — a future
    // scenario-apply, partial re-migration, or reset bypassing the guard —
    // re-running the migration must NOT clobber the already-migrated workflow
    // hotkeys. Two mechanisms keep them stable: the DICTATION hotkey is now KEPT
    // in its legacy field, so the rerun re-derives the same value from it
    // directly; the (still-cleared) NOTE/LISTEN legacy fields read back as `""`,
    // so `overlay_hotkey` reuses the existing overlay's hotkey instead.
    #[test]
    fn migrate_rerun_after_flag_reset_preserves_hotkeys() {
        let mut cfg = AppConfig::default();
        let custom = BTreeMap::new();

        assert!(migrate_to_workflows(&mut cfg, &custom), "first migration changes config");
        let dictation_hotkey =
            cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap().hotkey.clone();
        let note_hotkey = cfg.workflows.iter().find(|w| w.id == "wf.note").unwrap().hotkey.clone();
        let listen_hotkey =
            cfg.workflows.iter().find(|w| w.id == "wf.listen").unwrap().hotkey.clone();
        assert_eq!(dictation_hotkey, "cmd+shift+space");
        assert_eq!(note_hotkey, "option+n");
        assert_eq!(listen_hotkey, "option+l");
        let workflow_count_after_first = cfg.workflows.len();

        // Simulate a guard bypass: the flag is reset but the legacy fields are
        // NOT restored (rule 6 already cleared them on the first pass).
        cfg.workflow_migration_done = false;
        assert!(migrate_to_workflows(&mut cfg, &custom), "rerun still reports a change");

        // Hotkeys must be unchanged, not emptied.
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").expect("wf.dictation");
        let n = cfg.workflows.iter().find(|w| w.id == "wf.note").expect("wf.note");
        let l = cfg.workflows.iter().find(|w| w.id == "wf.listen").expect("wf.listen");
        assert_eq!(d.hotkey, dictation_hotkey, "dictation hotkey preserved across rerun");
        assert_eq!(n.hotkey, note_hotkey, "note hotkey preserved across rerun");
        assert_eq!(l.hotkey, listen_hotkey, "listen hotkey preserved across rerun");

        // No duplicate workflow ids: the rerun must overlay in place, not append.
        assert_eq!(cfg.workflows.len(), workflow_count_after_first, "no new workflows added");
        let ids: Vec<&str> = cfg.workflows.iter().map(|w| w.id.as_str()).collect();
        let unique: std::collections::HashSet<&str> = ids.iter().copied().collect();
        assert_eq!(ids.len(), unique.len(), "no duplicate workflow ids after rerun");
    }

    #[test]
    fn migrate_returns_false_when_already_done() {
        let mut cfg = AppConfig { workflow_migration_done: true, ..Default::default() };
        // Pre-set flag ⇒ short-circuit; the dictation hotkey is left untouched.
        assert!(!migrate_to_workflows(&mut cfg, &BTreeMap::new()));
        assert_eq!(cfg.hotkey_dictation, "cmd+shift+space");
        assert!(cfg.workflows.is_empty());
    }

    // ── Fix: Linux dictation hotkey survives migration ──────────────────────
    // Linux registers global shortcuts by reading config.hotkey_dictation /
    // hotkey_dictation_toggle DIRECTLY (main.rs), not effective_workflows, so
    // migration must NOT clear them — otherwise post-migration Linux registers no
    // dictation shortcut (a regression). macOS ignores these fields entirely
    // (build_hotkey_configs iterates effective_workflows).
    #[test]
    fn migration_keeps_dictation_hotkey_fields_for_linux() {
        let mut cfg = AppConfig {
            hotkey_dictation_toggle: "cmd+shift+d".into(),
            ..Default::default()
        };
        // Default hotkey_dictation is "cmd+shift+space".
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        assert_eq!(
            cfg.hotkey_dictation, "cmd+shift+space",
            "hold-to-talk dictation hotkey survives (Linux reads it directly)"
        );
        assert_eq!(
            cfg.hotkey_dictation_toggle, "cmd+shift+d",
            "toggle dictation hotkey survives (Linux reads it directly)"
        );

        // Same values are mirrored into the workflows the macOS path reads.
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.hotkey, "cmd+shift+space");
        let t = cfg.workflows.iter().find(|w| w.id == "wf.dictation-toggle").unwrap();
        assert_eq!(t.hotkey, "cmd+shift+d");

        // The note/listen legacy fields ARE still cleared (only macOS ever read
        // them, and Task 10 deleted those readers; Linux never registered them).
        assert!(cfg.hotkey_note.is_empty(), "note hotkey still cleared");
        assert!(cfg.hotkey_listen.is_empty(), "listen hotkey still cleared");
    }

    // ── Rule 1: custom modes → llm widgets ──────────────────────────────────

    #[test]
    fn custom_mode_with_llm_content_becomes_llm_widget() {
        let mut cfg = AppConfig::default();
        let mut custom = BTreeMap::new();
        custom.insert(
            "mymode".to_string(),
            Mode {
                name: "My Mode".into(),
                icon: "🛠".into(),
                system: Some("You are custom.".into()),
                user_template: Some("transform {text}".into()),
                temperature: 0.7,
                max_tokens: 1000,
                output_language: "English".into(),
                vocab_books: vec!["bookA".into()],
                // STT fields that must be dropped:
                stt_model: "whisper-x".into(),
                stt_prompt: "hint".into(),
                model: "gpt-4o".into(),
                ..Default::default()
            },
        );

        assert!(migrate_to_workflows(&mut cfg, &custom));

        let w = cfg.widgets.iter().find(|w| w.id == "llm.mymode").expect("llm.mymode widget");
        assert_eq!(w.role, WidgetRole::Processor);
        assert_eq!(w.type_tag, "llm");
        assert_eq!(w.name, "My Mode");
        assert!(!w.builtin);

        // props round-trip back to LlmProps and match the source mode field-for-field.
        let props: LlmProps = serde_json::from_value(w.props.clone()).expect("props parse as LlmProps");
        assert_eq!(props.system.as_deref(), Some("You are custom."));
        assert_eq!(props.user_template.as_deref(), Some("transform {text}"));
        assert_eq!(props.temperature, 0.7);
        assert_eq!(props.max_tokens, 1000);
        assert_eq!(props.output_language, "English");
        assert_eq!(props.vocab_books, vec!["bookA".to_string()]);
        // STT/model fields are not mapped into LlmProps.
        assert_eq!(props.model_profile, "");
    }

    #[test]
    fn custom_mode_without_llm_content_generates_no_widget() {
        let mut cfg = AppConfig::default();
        let mut custom = BTreeMap::new();
        custom.insert(
            "plain".to_string(),
            Mode { name: "Plain".into(), system: None, user_template: None, ..Default::default() },
        );

        assert!(migrate_to_workflows(&mut cfg, &custom));
        assert!(!cfg.widgets.iter().any(|w| w.id == "llm.plain"), "no widget for content-less mode");
    }

    #[test]
    fn builtin_four_modes_are_not_regenerated_as_widgets() {
        let mut cfg = AppConfig::default();
        let mut custom = BTreeMap::new();
        // A user who edited the built-in "polish" mode: it should NOT overwrite
        // the built-in llm.polish widget (rule 1 skips the built-in four).
        custom.insert("polish".to_string(), llm_mode("Polished"));

        assert!(migrate_to_workflows(&mut cfg, &custom));
        assert!(
            !cfg.widgets.iter().any(|w| w.id == "llm.polish"),
            "the built-in four never generate override widgets"
        );
    }

    // ── Rule 2: dictation LLM step ──────────────────────────────────────────

    #[test]
    fn dictation_mode_builtin_appends_its_llm_widget() {
        let mut cfg = AppConfig { dictation_mode: "polish".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.processors, vec!["stt.default".to_string(), "llm.polish".to_string()]);
    }

    #[test]
    fn dictation_mode_custom_with_llm_appends_generated_widget() {
        let mut custom = BTreeMap::new();
        custom.insert("mine".to_string(), llm_mode("Mine"));
        let mut cfg = AppConfig { dictation_mode: "mine".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &custom));
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.processors, vec!["stt.default".to_string(), "llm.mine".to_string()]);
        assert!(cfg.widgets.iter().any(|w| w.id == "llm.mine"));
    }

    #[test]
    fn dictation_mode_custom_without_llm_stays_stt_only() {
        let mut custom = BTreeMap::new();
        custom.insert(
            "quiet".to_string(),
            Mode { name: "Quiet".into(), system: None, user_template: None, ..Default::default() },
        );
        let mut cfg = AppConfig { dictation_mode: "quiet".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &custom));
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.processors, vec!["stt.default".to_string()], "no LLM step for content-less mode");
    }

    #[test]
    fn dictation_toggle_hotkey_creates_toggle_workflow() {
        let mut cfg = AppConfig {
            hotkey_dictation_toggle: "cmd+shift+d".into(),
            dictation_mode: "polish".into(),
            ..Default::default()
        };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));
        let t = cfg
            .workflows
            .iter()
            .find(|w| w.id == "wf.dictation-toggle")
            .expect("wf.dictation-toggle");
        assert_eq!(t.name, "听写·切换");
        assert_eq!(t.hotkey, "cmd+shift+d");
        assert_eq!(t.source, "src.mic-toggle");
        // Same processors/outputs as the hold-to-talk dictation workflow.
        assert_eq!(t.processors, vec!["stt.default".to_string(), "llm.polish".to_string()]);
        assert_eq!(t.outputs, vec!["out.insert".to_string()]);
        assert!(!t.builtin);
    }

    // ── Rule 3: notebook shortcuts ──────────────────────────────────────────

    #[test]
    fn notebook_hotkeys_create_note_workflows_and_widgets() {
        let mut cfg = AppConfig {
            notebook_hotkey_1: 5,
            notebook_hotkey_2: 0, // unbound
            notebook_hotkey_3: 9,
            hotkey_note_1: "option+1".into(),
            hotkey_note_3: "option+3".into(),
            ..Default::default()
        };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        // N=1 → wf.note-1 + out.notebook-5.
        let w1 = cfg.workflows.iter().find(|w| w.id == "wf.note-1").expect("wf.note-1");
        assert_eq!(w1.hotkey, "option+1");
        assert_eq!(w1.source, "src.mic-hold");
        assert_eq!(w1.processors, vec!["stt.default".to_string()]);
        assert_eq!(w1.outputs, vec!["out.notebook-5".to_string()]);
        assert!(!w1.builtin);

        let nb5 = cfg.widgets.iter().find(|w| w.id == "out.notebook-5").expect("out.notebook-5");
        assert_eq!(nb5.role, WidgetRole::Output);
        assert_eq!(nb5.type_tag, "notebook");
        assert_eq!(nb5.props["container_id"], 5);
        assert!(!nb5.builtin);

        // N=3 → wf.note-3 + out.notebook-9.
        let w3 = cfg.workflows.iter().find(|w| w.id == "wf.note-3").expect("wf.note-3");
        assert_eq!(w3.outputs, vec!["out.notebook-9".to_string()]);
        assert!(cfg.widgets.iter().any(|w| w.id == "out.notebook-9"));

        // N=2 unbound → no workflow, no widget.
        assert!(!cfg.workflows.iter().any(|w| w.id == "wf.note-2"));
    }

    // ── Rule 4: listen voice override ───────────────────────────────────────

    #[test]
    fn listen_voice_settings_land_in_out_speak_override() {
        let mut cfg = AppConfig {
            listen_mode: "listen".into(),
            listen_voice_profile: "prof-1".into(),
            listen_voice: "am_echo".into(),
            ..Default::default()
        };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        let sp = cfg.widgets.iter().find(|w| w.id == "out.speak").expect("out.speak override");
        assert_eq!(sp.type_tag, "speak");
        assert_eq!(sp.props["voice_profile"], "prof-1");
        assert_eq!(sp.props["voice"], "am_echo");

        let l = cfg.workflows.iter().find(|w| w.id == "wf.listen").unwrap();
        assert_eq!(l.processors, vec!["llm.listen".to_string()]);
        assert_eq!(l.outputs, vec!["out.speak".to_string()]);
    }

    // ── Fix: built-in content-bearing mode referenced by listen/text-action ──
    // A built-in mode with LLM content that ships NO `llm.*` widget (e.g.
    // `note`, unlike polish/formal/translate/summarize/listen) must have its
    // `llm.{id}` widget GENERATED from the built-in mode, or the reference
    // dangles and the workflow silently fails to instantiate.

    #[test]
    fn listen_mode_note_generates_llm_note_widget_from_builtin() {
        let mut cfg = AppConfig { listen_mode: "note".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        let w = cfg.widgets.iter().find(|w| w.id == "llm.note").expect("llm.note generated");
        assert_eq!(w.role, WidgetRole::Processor);
        assert_eq!(w.type_tag, "llm");
        assert!(!w.builtin);

        // Prompt/temperature are sourced faithfully from the built-in note mode.
        let props: LlmProps = serde_json::from_value(w.props.clone()).expect("props parse");
        let builtin_note = &crate::modes::built_in_modes()["note"];
        assert_eq!(
            props.system, builtin_note.system,
            "generated llm.note system matches built_in_modes()[\"note\"].system"
        );
        assert_eq!(props.user_template, builtin_note.user_template);
        assert_eq!(props.temperature, builtin_note.temperature);

        // wf.listen references the generated widget (not dangling).
        let l = cfg.workflows.iter().find(|w| w.id == "wf.listen").unwrap();
        assert_eq!(l.processors, vec!["llm.note".to_string()]);
    }

    // ── Rule 5: text actions → workflows, five target mapping, cleared ──────

    #[test]
    fn text_actions_map_to_workflows_with_target_outputs_and_clear() {
        let mut cfg = AppConfig::default();
        cfg.text_actions = vec![
            TextActionBinding { hotkey: "cmd+1".into(), mode_id: "polish".into(), output_target: OutputTarget::FloatingPopup },
            TextActionBinding { hotkey: "cmd+2".into(), mode_id: "formal".into(), output_target: OutputTarget::ActiveTextField },
            TextActionBinding { hotkey: "cmd+3".into(), mode_id: "translate".into(), output_target: OutputTarget::Clipboard },
            TextActionBinding { hotkey: "cmd+4".into(), mode_id: "summarize".into(), output_target: OutputTarget::AppendToContainer },
            TextActionBinding { hotkey: "cmd+5".into(), mode_id: "polish".into(), output_target: OutputTarget::None },
        ];

        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        let ta = |i: usize| -> &WorkflowDef {
            cfg.workflows
                .iter()
                .find(|w| w.id == format!("wf.ta-{i}"))
                .unwrap_or_else(|| panic!("wf.ta-{i} missing"))
        };

        // index 0: floating_popup → out.panel.
        let t0 = ta(0);
        assert_eq!(t0.hotkey, "cmd+1");
        assert_eq!(t0.source, "src.selection");
        assert_eq!(t0.processors, vec!["llm.polish".to_string()]);
        assert_eq!(t0.outputs, vec!["out.panel".to_string()]);
        assert_eq!(t0.name, "文本动作 Polish");
        assert!(!t0.builtin);

        // The full five-target mapping.
        assert_eq!(ta(1).outputs, vec!["out.insert".to_string()], "active_text_field → out.insert");
        assert_eq!(ta(2).outputs, vec!["out.clipboard".to_string()], "clipboard → out.clipboard");
        assert_eq!(ta(3).outputs, vec!["out.quicknote".to_string()], "append_to_container → out.quicknote");
        assert_eq!(ta(4).outputs, vec!["out.clipboard".to_string()], "none → out.clipboard");

        // Processor ids and hotkeys carried through.
        assert_eq!(ta(1).processors, vec!["llm.formal".to_string()]);
        assert_eq!(ta(2).processors, vec!["llm.translate".to_string()]);
        assert_eq!(ta(3).processors, vec!["llm.summarize".to_string()]);
        assert_eq!(ta(4).hotkey, "cmd+5");

        // Legacy text_actions are cleared to prevent double-registration.
        assert!(cfg.text_actions.is_empty());
    }

    #[test]
    fn text_action_name_uses_custom_mode_display_name() {
        let mut custom = BTreeMap::new();
        custom.insert("mine".to_string(), llm_mode("我的模式"));
        let mut cfg = AppConfig::default();
        cfg.text_actions = vec![TextActionBinding {
            hotkey: "cmd+9".into(),
            mode_id: "mine".into(),
            output_target: OutputTarget::FloatingPopup,
        }];

        assert!(migrate_to_workflows(&mut cfg, &custom));
        let t0 = cfg.workflows.iter().find(|w| w.id == "wf.ta-0").unwrap();
        assert_eq!(t0.name, "文本动作 我的模式");
        assert_eq!(t0.processors, vec!["llm.mine".to_string()]);
    }

    // ── Coherence: no migrated workflow references a non-existent widget ────

    #[test]
    fn migrated_config_has_no_dangling_widget_references() {
        use crate::workflow::engine::{effective_widgets, effective_workflows};

        // A config exercising every rule at once, including the built-in
        // content-bearing `note` mode (which ships NO llm.note widget) as both
        // the listen mode and a text-action target, plus a content-less `raw`
        // text-action whose LLM step must be DROPPED (not dangled).
        let mut custom = BTreeMap::new();
        custom.insert("mine".to_string(), llm_mode("Mine"));
        let mut cfg = AppConfig {
            dictation_mode: "mine".into(), // custom LLM dictation step
            hotkey_dictation_toggle: "cmd+shift+d".into(),
            notebook_hotkey_1: 5,
            notebook_hotkey_2: 7,
            listen_mode: "note".into(), // built-in content-bearing mode, no shipped widget
            listen_voice_profile: "p".into(),
            listen_voice: "v".into(),
            ..Default::default()
        };
        cfg.text_actions = vec![
            TextActionBinding { hotkey: "cmd+1".into(), mode_id: "translate".into(), output_target: OutputTarget::FloatingPopup },
            TextActionBinding { hotkey: "cmd+2".into(), mode_id: "mine".into(), output_target: OutputTarget::AppendToContainer },
            TextActionBinding { hotkey: "cmd+3".into(), mode_id: "note".into(), output_target: OutputTarget::ActiveTextField },
            TextActionBinding { hotkey: "cmd+4".into(), mode_id: "raw".into(), output_target: OutputTarget::Clipboard },
        ];

        assert!(migrate_to_workflows(&mut cfg, &custom));

        // The built-in `note` mode has LLM content but no shipped llm.note
        // widget — migration must GENERATE it (carrying note's prompt), or both
        // wf.listen and the note text-action would dangle.
        let note_widget =
            cfg.widgets.iter().find(|w| w.id == "llm.note").expect("llm.note widget generated");
        let note_props: LlmProps =
            serde_json::from_value(note_widget.props.clone()).expect("llm.note props parse");
        assert_eq!(
            note_props.system,
            crate::modes::built_in_modes()["note"].system,
            "generated llm.note carries the built-in note mode's system prompt"
        );

        // wf.listen and the note text-action reference the generated llm.note.
        let listen = cfg.workflows.iter().find(|w| w.id == "wf.listen").unwrap();
        assert_eq!(listen.processors, vec!["llm.note".to_string()]);
        let note_ta =
            cfg.workflows.iter().find(|w| w.hotkey == "cmd+3").expect("note text-action");
        assert_eq!(note_ta.processors, vec!["llm.note".to_string()]);

        // The `raw` text-action DROPS its LLM step (no dangling llm.raw); it
        // echoes the raw selection to its output.
        let raw_ta = cfg.workflows.iter().find(|w| w.hotkey == "cmd+4").expect("raw text-action");
        assert!(raw_ta.processors.is_empty(), "raw text-action has no llm.raw processor");
        assert_eq!(raw_ta.outputs, vec!["out.clipboard".to_string()]);

        // Coherence: every effective workflow's source/processors/outputs must
        // resolve to a widget in the effective widget set (built-ins overlaid by
        // config). This is the check that would fail on a dangling llm.note.
        let widget_ids: std::collections::HashSet<String> =
            effective_widgets(&cfg).into_iter().map(|w| w.id).collect();
        for wf in effective_workflows(&cfg) {
            assert!(widget_ids.contains(&wf.source), "{}: source '{}' missing", wf.id, wf.source);
            for p in &wf.processors {
                assert!(widget_ids.contains(p), "{}: processor '{p}' missing", wf.id);
            }
            for o in &wf.outputs {
                assert!(widget_ids.contains(o), "{}: output '{o}' missing", wf.id);
            }
        }
    }

    // ── migrate_settings_into_flow (Workflow P2) ─────────────────────────────
    // One-shot relocation of three formerly-global settings (STT language,
    // insert strategy, translate target) onto widget props.

    #[test]
    fn relocation_seeds_nondefault_stt_language() {
        let mut cfg = AppConfig::default();
        cfg.stt_language = "Chinese".into();
        assert!(migrate_settings_into_flow(&mut cfg));
        let w = cfg.widgets.iter().find(|w| w.id == "stt.default").unwrap();
        assert_eq!(w.props.get("language").unwrap(), "Chinese");
    }

    #[test]
    fn relocation_seeds_nondefault_insert_strategy() {
        let mut cfg = AppConfig::default();
        // Pick whichever strategy is NOT the platform default so the test is
        // meaningful (and passes) on both Linux and macOS/Windows CI runners.
        let non_default = if cfg!(target_os = "linux") { "paste" } else { "type" };
        cfg.injection_strategy = non_default.to_string();
        assert!(migrate_settings_into_flow(&mut cfg));
        let w = cfg.widgets.iter().find(|w| w.id == "out.insert").unwrap();
        assert_eq!(w.props.get("strategy").unwrap(), non_default);
    }

    #[test]
    fn relocation_bakes_translate_target_into_prompt() {
        let mut cfg = AppConfig::default();
        cfg.translate_target = "Chinese".into();
        assert!(migrate_settings_into_flow(&mut cfg));
        let w = cfg.widgets.iter().find(|w| w.id == "llm.translate").unwrap();
        let ut = w.props.get("user_template").unwrap().as_str().unwrap();
        assert!(ut.contains("Chinese") && !ut.contains("{target_lang}"));
    }

    #[test]
    fn relocation_is_idempotent() {
        let mut cfg = AppConfig::default();
        cfg.stt_language = "Chinese".into();
        assert!(migrate_settings_into_flow(&mut cfg));
        assert!(!migrate_settings_into_flow(&mut cfg)); // sentinel set → no-op
    }

    #[test]
    fn relocation_noop_for_defaults() {
        let mut cfg = AppConfig::default(); // stt=auto, target=English, strategy=platform-default
        assert!(migrate_settings_into_flow(&mut cfg));
        assert!(cfg.widgets.iter().all(|w| w.id != "stt.default"), "no override needed for default stt");
        assert!(cfg.widgets.iter().all(|w| w.id != "out.insert"), "no override needed for default strategy");
        assert!(cfg.widgets.iter().all(|w| w.id != "llm.translate"), "no override needed for default target");
        assert!(cfg.widgets.is_empty(), "an all-default config seeds zero override widgets");
    }

    // ── remap_renamed_builtins: out.dialog-explain → out.dialog ──────────────

    /// A stale `out.dialog-explain` widget entry and any workflow output that
    /// references it are both renamed to `out.dialog`.
    #[test]
    fn remap_renames_dialog_widget_and_workflow_refs() {
        let mut cfg = AppConfig::default();
        cfg.widgets.push(WidgetDef {
            id: "out.dialog-explain".into(),
            role: WidgetRole::Output,
            type_tag: "dialog".into(),
            name: "解释对话框".into(),
            icon: "💬".into(),
            props: serde_json::json!({}),
            builtin: true,
        });
        cfg.workflows.push(WorkflowDef {
            id: "wf.explain".into(),
            name: "选中解释".into(),
            icon: "💡".into(),
            hotkey: String::new(),
            triggers: Vec::new(),
            source: "src.selection".into(),
            processors: vec!["llm.explain".into()],
            outputs: vec!["out.dialog-explain".into()],
            builtin: true,
        });

        assert!(remap_renamed_builtins(&mut cfg), "first pass reports a change");

        assert!(cfg.widgets.iter().any(|w| w.id == "out.dialog"), "widget id renamed");
        assert!(!cfg.widgets.iter().any(|w| w.id == "out.dialog-explain"), "old widget id gone");
        let wf = cfg.workflows.iter().find(|w| w.id == "wf.explain").unwrap();
        assert_eq!(wf.outputs, vec!["out.dialog".to_string()], "workflow output ref renamed");
    }

    /// If both the old and new widget ids are present, the stale old entry is
    /// dropped (not renamed) so no duplicate `out.dialog` id results.
    #[test]
    fn remap_drops_stale_old_widget_when_new_already_exists() {
        let mut cfg = AppConfig::default();
        for id in ["out.dialog-explain", "out.dialog"] {
            cfg.widgets.push(WidgetDef {
                id: id.into(),
                role: WidgetRole::Output,
                type_tag: "dialog".into(),
                name: "对话框".into(),
                icon: "💬".into(),
                props: serde_json::json!({}),
                builtin: true,
            });
        }

        assert!(remap_renamed_builtins(&mut cfg), "reports a change (stale dropped)");
        assert_eq!(
            cfg.widgets.iter().filter(|w| w.id == "out.dialog").count(),
            1,
            "exactly one out.dialog entry — no duplicate"
        );
        assert!(!cfg.widgets.iter().any(|w| w.id == "out.dialog-explain"), "stale entry dropped");
    }

    /// Idempotent: a second pass over an already-remapped config is a no-op.
    #[test]
    fn remap_is_idempotent() {
        let mut cfg = AppConfig::default();
        cfg.widgets.push(WidgetDef {
            id: "out.dialog-explain".into(),
            role: WidgetRole::Output,
            type_tag: "dialog".into(),
            name: "解释对话框".into(),
            icon: "💬".into(),
            props: serde_json::json!({}),
            builtin: true,
        });
        assert!(remap_renamed_builtins(&mut cfg), "first pass changes config");
        assert!(!remap_renamed_builtins(&mut cfg), "second pass is a no-op");
    }

    /// A fresh (already-current) config with no stale ids is untouched.
    #[test]
    fn remap_noop_on_fresh_config() {
        let mut cfg = AppConfig::default();
        assert!(!remap_renamed_builtins(&mut cfg), "fresh config: nothing to remap");
        assert!(cfg.widgets.is_empty() && cfg.workflows.is_empty());
    }

    // ── migrate_hotkeys_to_triggers (Workbench P1) ───────────────────────────

    #[test]
    fn hotkeys_migrate_to_triggers_with_capture() {
        let mut cfg = AppConfig::default();
        // 覆盖一条内建麦克风配方（整体 overlay，模拟用户改过快捷键）——source
        // 是 src.mic-hold（capture "hold"）。
        let mut mic_wf = crate::workflow::builtin::built_in_workflows()
            .into_iter()
            .find(|w| {
                crate::workflow::builtin::built_in_widgets()
                    .iter()
                    .any(|wd| wd.id == w.source && wd.type_tag == "microphone")
            })
            .unwrap();
        assert_eq!(mic_wf.source, "src.mic-hold", "sanity: this fixture's source is the hold mic");
        mic_wf.hotkey = "cmd+shift+space".into();
        mic_wf.triggers.clear(); // overlay 整体替换后 seeds 丢失的情形
        cfg.workflows.push(mic_wf.clone());
        // 一条自定义划词配方（非麦克风 source）。
        cfg.workflows.push(WorkflowDef {
            id: "wf.custom-1".into(),
            name: "T".into(),
            icon: String::new(),
            hotkey: "cmd+shift+t".into(),
            source: "src.selection".into(),
            processors: vec![],
            outputs: vec!["out.panel".into()],
            builtin: false,
            triggers: vec![],
        });
        // 一条 overlay/custom 配方，source 是 src.mic-toggle（capture
        // "toggle"）—— 用来区分"capture 真的从 source 传播"和"helper 默认值
        // 恒为 hold"这两种情况：如果实现有 bug 总是写 capture: None，这条
        // fixture 的 hotkey_triggers() 会读回 "hold" 而不是 "toggle"，从而
        // 被下面的断言抓到（第一条 mic-hold fixture 无法区分这两种情况，因为
        // None 和 "hold" 读回来一样）。
        cfg.workflows.push(WorkflowDef {
            id: "wf.custom-toggle".into(),
            name: "Toggle".into(),
            icon: String::new(),
            hotkey: "cmd+shift+g".into(),
            source: "src.mic-toggle".into(),
            processors: vec![],
            outputs: vec!["out.insert".into()],
            builtin: false,
            triggers: vec![],
        });

        assert!(migrate_hotkeys_to_triggers(&mut cfg));

        let m = &cfg.workflows[0];
        assert!(m.hotkey.is_empty());
        let hk: Vec<_> = m.hotkey_triggers().collect();
        assert_eq!(hk.len(), 1);
        assert_eq!(hk[0].1, "cmd+shift+space");
        assert_eq!(hk[0].2, "hold", "capture propagated from src.mic-hold's capture prop");
        // Finding 4: the first backfilled PillSlot lands at order 1000 (after
        // the builtin seeds' 0/10/20…).
        assert_eq!(m.pill_order(), Some(1000), "first backfilled mic overlay gets order 1000");

        let c = &cfg.workflows[1];
        assert!(c.hotkey.is_empty());
        assert_eq!(c.hotkey_triggers().next().unwrap().1, "cmd+shift+t");
        assert_eq!(c.hotkey_triggers().next().unwrap().2, "hold"); // 非 mic 无 capture
        assert!(c.pill_order().is_none());

        let g = &cfg.workflows[2];
        assert!(g.hotkey.is_empty());
        let hk_g: Vec<_> = g.hotkey_triggers().collect();
        assert_eq!(hk_g.len(), 1);
        assert_eq!(hk_g[0].1, "cmd+shift+g");
        assert_eq!(hk_g[0].2, "toggle", "capture propagated from src.mic-toggle's capture prop");
        // Finding 4: the second backfilled PillSlot lands at 1000+10.
        assert_eq!(g.pill_order(), Some(1010), "second backfilled mic overlay gets order 1010");

        // 幂等（哨兵）
        assert!(!migrate_hotkeys_to_triggers(&mut cfg));
    }

    // ── Finding 2: an already-present Hotkey chip for the same combo as the
    // legacy `hotkey` field must not be duplicated. ─────────────────────────
    #[test]
    fn hotkeys_migrate_skips_duplicate_combo_already_present() {
        let mut cfg = AppConfig::default();
        cfg.workflows.push(WorkflowDef {
            id: "wf.custom-dup".into(),
            name: "Dup".into(),
            icon: String::new(),
            hotkey: "cmd+shift+x".into(),
            source: "src.selection".into(),
            processors: vec![],
            outputs: vec!["out.panel".into()],
            builtin: false,
            triggers: vec![Trigger::Hotkey { combo: "cmd+shift+x".into(), capture: None }],
        });

        assert!(migrate_hotkeys_to_triggers(&mut cfg));

        let wf = cfg.workflows.iter().find(|w| w.id == "wf.custom-dup").unwrap();
        assert!(wf.hotkey.is_empty(), "legacy hotkey field is always cleared");
        let matching: Vec<_> =
            wf.hotkey_triggers().filter(|(_, c, _)| *c == "cmd+shift+x").collect();
        assert_eq!(matching.len(), 1, "exactly one hotkey chip for the combo — no duplicate");
    }

    // ── Finding 3: an empty legacy hotkey on a non-microphone source produces
    // no trigger chips at all (no Hotkey, no PillSlot). ─────────────────────
    #[test]
    fn hotkeys_migrate_empty_hotkey_nonmic_source_yields_no_triggers() {
        let mut cfg = AppConfig::default();
        cfg.workflows.push(WorkflowDef {
            id: "wf.custom-empty".into(),
            name: "Empty".into(),
            icon: String::new(),
            hotkey: String::new(),
            source: "src.selection".into(),
            processors: vec![],
            outputs: vec!["out.panel".into()],
            builtin: false,
            triggers: vec![],
        });

        assert!(migrate_hotkeys_to_triggers(&mut cfg));

        let wf = cfg.workflows.iter().find(|w| w.id == "wf.custom-empty").unwrap();
        assert!(
            wf.triggers.is_empty(),
            "empty hotkey + non-mic source produces zero trigger chips"
        );
    }
}
