//! One-time migration of legacy config (modes / dictation / note / listen /
//! text-actions) into the workflow model (Workflow P1).
//!
//! [`migrate_to_workflows`] rewrites the legacy hotkey + mode fields of an
//! [`AppConfig`] into overlay [`WorkflowDef`]s / [`WidgetDef`]s in
//! `config.workflows` / `config.widgets`, then clears the legacy hotkey fields
//! so the old code paths (and Task 10's hotkey registration) cannot
//! double-register. It is idempotent: guarded by `config.workflow_migration_done`
//! and a no-op (returning `false`) once that flag is set.

use std::collections::BTreeMap;

use crate::config::AppConfig;
use crate::modes::{Mode, OutputTarget};
use crate::workflow::llm_step::LlmProps;
use crate::workflow::model::{WidgetDef, WidgetRole, WorkflowDef};

/// Built-in mode ids that already ship as `llm.*` processor widgets and so are
/// never regenerated by rule 1. (`listen` also has a built-in widget but is
/// deliberately *not* skipped here — a user who customized their "listen" mode
/// should override `llm.listen`; see [`mode_resolves_to_llm_widget`].)
const BUILTIN_LLM_MODE_IDS: [&str; 4] = ["polish", "formal", "translate", "summarize"];

/// Every built-in `llm.*` widget's backing mode id — the set that always
/// resolves to a valid `llm.{id}` widget without migration having to generate it.
const BUILTIN_LLM_WIDGET_IDS: [&str; 5] = ["polish", "formal", "translate", "summarize", "listen"];

/// One-time migration of legacy config into the workflow model.
///
/// Rewrites the legacy dictation / note / listen / text-action hotkey + mode
/// fields of `config` into overlay [`WorkflowDef`]s / [`WidgetDef`]s (pushed
/// into `config.workflows` / `config.widgets`, replacing any built-in of the
/// same id wholesale via [`crate::workflow::engine::effective_workflows`]), then
/// clears the legacy hotkey fields so nothing double-registers. `custom_modes`
/// is the user's `modes.json` map (desktop passes
/// [`crate::modes::load_custom_modes`]; tests pass a hand-built map).
///
/// Idempotent: returns `false` immediately when `config.workflow_migration_done`
/// is already set, and otherwise sets it before returning `true`. A `true`
/// return means the caller should persist `config`.
pub fn migrate_to_workflows(config: &mut AppConfig, custom_modes: &BTreeMap<String, Mode>) -> bool {
    if config.workflow_migration_done {
        return false;
    }

    // ── Rule 1: custom modes with LLM content → `llm.{id}` processor widgets ──
    // The built-in four are skipped (already built-in widgets). STT/model
    // fields are dropped; `vocab_books` is carried over.
    for (mode_id, mode) in custom_modes {
        if BUILTIN_LLM_MODE_IDS.contains(&mode_id.as_str()) {
            continue;
        }
        if mode.system.is_none() && mode.user_template.is_none() {
            continue;
        }
        let props = LlmProps {
            system: mode.system.clone(),
            user_template: mode.user_template.clone(),
            // Legacy `Mode.model` is a model identifier, not a profile id; there
            // is no faithful mapping, so fall back to the global LLM profile.
            model_profile: String::new(),
            temperature: mode.temperature,
            max_tokens: mode.max_tokens,
            output_language: mode.output_language.clone(),
            vocab_books: mode.vocab_books.clone(),
        };
        let props = serde_json::to_value(&props).unwrap_or_else(|_| serde_json::json!({}));
        upsert_widget(
            config,
            WidgetDef {
                id: format!("llm.{mode_id}"),
                role: WidgetRole::Processor,
                type_tag: "llm".to_string(),
                name: mode.name.clone(),
                icon: mode.icon.clone(),
                props,
                builtin: false,
            },
        );
    }

    // ── Rule 2: dictation ──
    // processors = [stt.default] (+ llm.{dictation_mode} when not "raw" and that
    // mode resolves to a real llm widget).
    let mut dictation_processors = vec!["stt.default".to_string()];
    if config.dictation_mode != "raw"
        && mode_resolves_to_llm_widget(&config.dictation_mode, custom_modes)
    {
        dictation_processors.push(format!("llm.{}", config.dictation_mode));
    }
    upsert_workflow(
        config,
        WorkflowDef {
            id: "wf.dictation".to_string(),
            name: "听写".to_string(),
            icon: "🎤".to_string(),
            hotkey: config.hotkey_dictation.clone(),
            source: "src.mic-hold".to_string(),
            processors: dictation_processors.clone(),
            outputs: vec!["out.insert".to_string()],
            builtin: true,
        },
    );
    if !config.hotkey_dictation_toggle.is_empty() {
        upsert_workflow(
            config,
            WorkflowDef {
                id: "wf.dictation-toggle".to_string(),
                name: "听写·切换".to_string(),
                icon: "🎤".to_string(),
                hotkey: config.hotkey_dictation_toggle.clone(),
                source: "src.mic-toggle".to_string(),
                processors: dictation_processors,
                outputs: vec!["out.insert".to_string()],
                builtin: false,
            },
        );
    }

    // ── Rule 3: note (faithful — STT only, no LLM step) ──
    upsert_workflow(
        config,
        WorkflowDef {
            id: "wf.note".to_string(),
            name: "记笔记".to_string(),
            icon: "📓".to_string(),
            hotkey: config.hotkey_note.clone(),
            source: "src.mic-hold".to_string(),
            processors: vec!["stt.default".to_string()],
            outputs: vec!["out.quicknote".to_string()],
            builtin: true,
        },
    );
    let notebooks = [
        (1, config.notebook_hotkey_1, config.hotkey_note_1.clone()),
        (2, config.notebook_hotkey_2, config.hotkey_note_2.clone()),
        (3, config.notebook_hotkey_3, config.hotkey_note_3.clone()),
    ];
    for (n, container_id, hotkey) in notebooks {
        if container_id <= 0 {
            continue;
        }
        let widget_id = format!("out.notebook-{container_id}");
        upsert_widget(
            config,
            WidgetDef {
                id: widget_id.clone(),
                role: WidgetRole::Output,
                type_tag: "notebook".to_string(),
                name: format!("笔记本 {container_id}"),
                icon: "📓".to_string(),
                props: serde_json::json!({ "container_id": container_id }),
                builtin: false,
            },
        );
        upsert_workflow(
            config,
            WorkflowDef {
                id: format!("wf.note-{n}"),
                name: format!("记笔记 {n}"),
                icon: "📓".to_string(),
                hotkey,
                source: "src.mic-hold".to_string(),
                processors: vec!["stt.default".to_string()],
                outputs: vec![widget_id],
                builtin: false,
            },
        );
    }

    // ── Rule 4: listen (selection → llm.{listen_mode} → speak) ──
    upsert_workflow(
        config,
        WorkflowDef {
            id: "wf.listen".to_string(),
            name: "朗读".to_string(),
            icon: "🎧".to_string(),
            hotkey: config.hotkey_listen.clone(),
            source: "src.selection".to_string(),
            processors: vec![format!("llm.{}", config.listen_mode)],
            outputs: vec!["out.speak".to_string()],
            builtin: true,
        },
    );
    // Overlay out.speak with the listen voice settings.
    upsert_widget(
        config,
        WidgetDef {
            id: "out.speak".to_string(),
            role: WidgetRole::Output,
            type_tag: "speak".to_string(),
            name: "朗读".to_string(),
            icon: "🔊".to_string(),
            props: serde_json::json!({
                "voice_profile": config.listen_voice_profile.clone(),
                "voice": config.listen_voice.clone(),
            }),
            builtin: true,
        },
    );

    // ── Rule 5: text actions → wf.ta-{i}, cleared afterward ──
    // Move the bindings out first so the loop can borrow `config` mutably; this
    // also clears `config.text_actions` (prevents double-registration).
    let text_actions = std::mem::take(&mut config.text_actions);
    for (i, binding) in text_actions.iter().enumerate() {
        let name = format!("文本动作 {}", resolve_mode_name(&binding.mode_id, custom_modes));
        upsert_workflow(
            config,
            WorkflowDef {
                id: format!("wf.ta-{i}"),
                name,
                icon: "✨".to_string(),
                hotkey: binding.hotkey.clone(),
                source: "src.selection".to_string(),
                processors: vec![format!("llm.{}", binding.mode_id)],
                outputs: vec![output_id_for_target(&binding.output_target).to_string()],
                builtin: false,
            },
        );
    }

    // ── Rule 6: clear legacy hotkey fields (values now live in workflows) ──
    // `dictation_mode` is intentionally preserved (Task 13 keeps the field).
    config.hotkey_dictation.clear();
    config.hotkey_dictation_toggle.clear();
    config.hotkey_note.clear();
    config.hotkey_note_1.clear();
    config.hotkey_note_2.clear();
    config.hotkey_note_3.clear();
    config.hotkey_listen.clear();

    config.workflow_migration_done = true;
    true
}

/// Does `mode_id` resolve to a real `llm.{mode_id}` processor widget — either a
/// built-in one, or one that rule 1 generates from a content-bearing custom
/// mode? Used to decide whether to append an LLM step to the dictation
/// pipeline, so a mode with no widget (e.g. built-in `note`, which has no
/// `llm.note` widget) never produces a dangling reference.
fn mode_resolves_to_llm_widget(mode_id: &str, custom_modes: &BTreeMap<String, Mode>) -> bool {
    if BUILTIN_LLM_WIDGET_IDS.contains(&mode_id) {
        return true;
    }
    custom_modes
        .get(mode_id)
        .is_some_and(|m| m.system.is_some() || m.user_template.is_some())
}

/// The display name for `mode_id`: the custom mode's name if present, else the
/// built-in mode's name, else the id itself.
fn resolve_mode_name(mode_id: &str, custom_modes: &BTreeMap<String, Mode>) -> String {
    if let Some(m) = custom_modes.get(mode_id) {
        return m.name.clone();
    }
    if let Some(m) = crate::modes::built_in_modes().get(mode_id) {
        return m.name.clone();
    }
    mode_id.to_string()
}

/// Map a legacy [`OutputTarget`] onto the output-widget id a text-action
/// workflow delivers to.
fn output_id_for_target(target: &OutputTarget) -> &'static str {
    match target {
        OutputTarget::FloatingPopup => "out.panel",
        OutputTarget::ActiveTextField => "out.insert",
        OutputTarget::Clipboard => "out.clipboard",
        OutputTarget::AppendToContainer => "out.quicknote",
        OutputTarget::None => "out.clipboard",
    }
}

/// Insert `widget` into `config.widgets`, replacing any existing entry with the
/// same id (idempotent; also dedupes notebook widgets that share a container id).
fn upsert_widget(config: &mut AppConfig, widget: WidgetDef) {
    match config.widgets.iter_mut().find(|w| w.id == widget.id) {
        Some(slot) => *slot = widget,
        None => config.widgets.push(widget),
    }
}

/// Insert `workflow` into `config.workflows`, replacing any existing entry with
/// the same id.
fn upsert_workflow(config: &mut AppConfig, workflow: WorkflowDef) {
    match config.workflows.iter_mut().find(|w| w.id == workflow.id) {
        Some(slot) => *slot = workflow,
        None => config.workflows.push(workflow),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::TextActionBinding;

    /// A custom mode carrying LLM content (system + user_template).
    fn llm_mode(name: &str) -> Mode {
        Mode {
            name: name.to_string(),
            system: Some(format!("You are {name}.")),
            user_template: Some("do <<<{text}>>>".to_string()),
            ..Default::default()
        }
    }

    // ── Rule: default config produces the expected full shape ───────────────

    #[test]
    fn migrate_default_config_produces_expected_shape() {
        let mut cfg = AppConfig::default();
        let custom = BTreeMap::new();

        let changed = migrate_to_workflows(&mut cfg, &custom);
        assert!(changed, "first migration reports a change");
        assert!(cfg.workflow_migration_done, "migration flag is set");

        // Exactly three workflow overlays for the default config: dictation,
        // note, listen (no toggle, no notebook-N, no text-actions).
        assert_eq!(cfg.workflows.len(), 3, "dictation + note + listen only");
        // Exactly one widget overlay: the out.speak listen-voice override.
        assert_eq!(cfg.widgets.len(), 1, "only the out.speak override");

        // wf.dictation overlay: the dictation hotkey lands here; raw mode ⇒ no
        // LLM step; mic-hold source; insert output; builtin preserved.
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").expect("wf.dictation");
        assert_eq!(d.hotkey, "cmd+shift+space");
        assert_eq!(d.source, "src.mic-hold");
        assert_eq!(d.processors, vec!["stt.default".to_string()]);
        assert_eq!(d.outputs, vec!["out.insert".to_string()]);
        assert!(d.builtin);

        // No toggle workflow: hotkey_dictation_toggle is empty by default.
        assert!(!cfg.workflows.iter().any(|w| w.id == "wf.dictation-toggle"));

        // wf.note overlay: note hotkey; STT only (no LLM — faithful); quicknote.
        let n = cfg.workflows.iter().find(|w| w.id == "wf.note").expect("wf.note");
        assert_eq!(n.hotkey, "option+n");
        assert_eq!(n.source, "src.mic-hold");
        assert_eq!(n.processors, vec!["stt.default".to_string()]);
        assert_eq!(n.outputs, vec!["out.quicknote".to_string()]);
        assert!(n.builtin);

        // No notebook-N workflows: notebook_hotkey_N are all 0 by default.
        assert!(!cfg.workflows.iter().any(|w| w.id.starts_with("wf.note-")));

        // wf.listen overlay: listen hotkey; llm.listen; speak output.
        let l = cfg.workflows.iter().find(|w| w.id == "wf.listen").expect("wf.listen");
        assert_eq!(l.hotkey, "option+l");
        assert_eq!(l.source, "src.selection");
        assert_eq!(l.processors, vec!["llm.listen".to_string()]);
        assert_eq!(l.outputs, vec!["out.speak".to_string()]);
        assert!(l.builtin);

        // out.speak override carries the (default) listen voice settings.
        let sp = cfg.widgets.iter().find(|w| w.id == "out.speak").expect("out.speak override");
        assert_eq!(sp.role, WidgetRole::Output);
        assert_eq!(sp.type_tag, "speak");
        assert_eq!(sp.props["voice_profile"], "");
        assert_eq!(sp.props["voice"], "default");

        // No text actions by default.
        assert!(!cfg.workflows.iter().any(|w| w.id.starts_with("wf.ta-")));
        assert!(cfg.text_actions.is_empty());

        // Rule 6: legacy hotkey fields are cleared; dictation_mode is preserved.
        assert!(cfg.hotkey_dictation.is_empty());
        assert!(cfg.hotkey_dictation_toggle.is_empty());
        assert!(cfg.hotkey_note.is_empty());
        assert!(cfg.hotkey_note_1.is_empty());
        assert!(cfg.hotkey_note_2.is_empty());
        assert!(cfg.hotkey_note_3.is_empty());
        assert!(cfg.hotkey_listen.is_empty());
        assert_eq!(cfg.dictation_mode, "raw");
    }

    // ── Rule: idempotency ───────────────────────────────────────────────────

    #[test]
    fn migrate_is_idempotent() {
        let mut cfg = AppConfig::default();
        let custom = BTreeMap::new();

        assert!(migrate_to_workflows(&mut cfg, &custom), "first call changes config");
        let workflows_after_first = cfg.workflows.clone();
        let widgets_after_first = cfg.widgets.clone();
        let dictation_mode_after_first = cfg.dictation_mode.clone();

        // Second call is a no-op: returns false, mutates nothing.
        assert!(!migrate_to_workflows(&mut cfg, &custom), "second call reports no change");
        assert_eq!(cfg.workflows, workflows_after_first, "workflows unchanged");
        assert_eq!(cfg.widgets, widgets_after_first, "widgets unchanged");
        assert_eq!(cfg.dictation_mode, dictation_mode_after_first);
        assert!(cfg.workflow_migration_done);
    }

    #[test]
    fn migrate_returns_false_when_already_done() {
        let mut cfg = AppConfig { workflow_migration_done: true, ..Default::default() };
        // Pre-set flag ⇒ short-circuit; the dictation hotkey is left untouched.
        assert!(!migrate_to_workflows(&mut cfg, &BTreeMap::new()));
        assert_eq!(cfg.hotkey_dictation, "cmd+shift+space");
        assert!(cfg.workflows.is_empty());
    }

    // ── Rule 1: custom modes → llm widgets ──────────────────────────────────

    #[test]
    fn custom_mode_with_llm_content_becomes_llm_widget() {
        let mut cfg = AppConfig::default();
        let mut custom = BTreeMap::new();
        custom.insert(
            "mymode".to_string(),
            Mode {
                name: "My Mode".into(),
                icon: "🛠".into(),
                system: Some("You are custom.".into()),
                user_template: Some("transform {text}".into()),
                temperature: 0.7,
                max_tokens: 1000,
                output_language: "English".into(),
                vocab_books: vec!["bookA".into()],
                // STT fields that must be dropped:
                stt_model: "whisper-x".into(),
                stt_prompt: "hint".into(),
                model: "gpt-4o".into(),
                ..Default::default()
            },
        );

        assert!(migrate_to_workflows(&mut cfg, &custom));

        let w = cfg.widgets.iter().find(|w| w.id == "llm.mymode").expect("llm.mymode widget");
        assert_eq!(w.role, WidgetRole::Processor);
        assert_eq!(w.type_tag, "llm");
        assert_eq!(w.name, "My Mode");
        assert!(!w.builtin);

        // props round-trip back to LlmProps and match the source mode field-for-field.
        let props: LlmProps = serde_json::from_value(w.props.clone()).expect("props parse as LlmProps");
        assert_eq!(props.system.as_deref(), Some("You are custom."));
        assert_eq!(props.user_template.as_deref(), Some("transform {text}"));
        assert_eq!(props.temperature, 0.7);
        assert_eq!(props.max_tokens, 1000);
        assert_eq!(props.output_language, "English");
        assert_eq!(props.vocab_books, vec!["bookA".to_string()]);
        // STT/model fields are not mapped into LlmProps.
        assert_eq!(props.model_profile, "");
    }

    #[test]
    fn custom_mode_without_llm_content_generates_no_widget() {
        let mut cfg = AppConfig::default();
        let mut custom = BTreeMap::new();
        custom.insert(
            "plain".to_string(),
            Mode { name: "Plain".into(), system: None, user_template: None, ..Default::default() },
        );

        assert!(migrate_to_workflows(&mut cfg, &custom));
        assert!(!cfg.widgets.iter().any(|w| w.id == "llm.plain"), "no widget for content-less mode");
    }

    #[test]
    fn builtin_four_modes_are_not_regenerated_as_widgets() {
        let mut cfg = AppConfig::default();
        let mut custom = BTreeMap::new();
        // A user who edited the built-in "polish" mode: it should NOT overwrite
        // the built-in llm.polish widget (rule 1 skips the built-in four).
        custom.insert("polish".to_string(), llm_mode("Polished"));

        assert!(migrate_to_workflows(&mut cfg, &custom));
        assert!(
            !cfg.widgets.iter().any(|w| w.id == "llm.polish"),
            "the built-in four never generate override widgets"
        );
    }

    // ── Rule 2: dictation LLM step ──────────────────────────────────────────

    #[test]
    fn dictation_mode_builtin_appends_its_llm_widget() {
        let mut cfg = AppConfig { dictation_mode: "polish".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.processors, vec!["stt.default".to_string(), "llm.polish".to_string()]);
    }

    #[test]
    fn dictation_mode_custom_with_llm_appends_generated_widget() {
        let mut custom = BTreeMap::new();
        custom.insert("mine".to_string(), llm_mode("Mine"));
        let mut cfg = AppConfig { dictation_mode: "mine".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &custom));
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.processors, vec!["stt.default".to_string(), "llm.mine".to_string()]);
        assert!(cfg.widgets.iter().any(|w| w.id == "llm.mine"));
    }

    #[test]
    fn dictation_mode_custom_without_llm_stays_stt_only() {
        let mut custom = BTreeMap::new();
        custom.insert(
            "quiet".to_string(),
            Mode { name: "Quiet".into(), system: None, user_template: None, ..Default::default() },
        );
        let mut cfg = AppConfig { dictation_mode: "quiet".into(), ..Default::default() };
        assert!(migrate_to_workflows(&mut cfg, &custom));
        let d = cfg.workflows.iter().find(|w| w.id == "wf.dictation").unwrap();
        assert_eq!(d.processors, vec!["stt.default".to_string()], "no LLM step for content-less mode");
    }

    #[test]
    fn dictation_toggle_hotkey_creates_toggle_workflow() {
        let mut cfg = AppConfig {
            hotkey_dictation_toggle: "cmd+shift+d".into(),
            dictation_mode: "polish".into(),
            ..Default::default()
        };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));
        let t = cfg
            .workflows
            .iter()
            .find(|w| w.id == "wf.dictation-toggle")
            .expect("wf.dictation-toggle");
        assert_eq!(t.name, "听写·切换");
        assert_eq!(t.hotkey, "cmd+shift+d");
        assert_eq!(t.source, "src.mic-toggle");
        // Same processors/outputs as the hold-to-talk dictation workflow.
        assert_eq!(t.processors, vec!["stt.default".to_string(), "llm.polish".to_string()]);
        assert_eq!(t.outputs, vec!["out.insert".to_string()]);
        assert!(!t.builtin);
    }

    // ── Rule 3: notebook shortcuts ──────────────────────────────────────────

    #[test]
    fn notebook_hotkeys_create_note_workflows_and_widgets() {
        let mut cfg = AppConfig {
            notebook_hotkey_1: 5,
            notebook_hotkey_2: 0, // unbound
            notebook_hotkey_3: 9,
            hotkey_note_1: "option+1".into(),
            hotkey_note_3: "option+3".into(),
            ..Default::default()
        };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        // N=1 → wf.note-1 + out.notebook-5.
        let w1 = cfg.workflows.iter().find(|w| w.id == "wf.note-1").expect("wf.note-1");
        assert_eq!(w1.hotkey, "option+1");
        assert_eq!(w1.source, "src.mic-hold");
        assert_eq!(w1.processors, vec!["stt.default".to_string()]);
        assert_eq!(w1.outputs, vec!["out.notebook-5".to_string()]);
        assert!(!w1.builtin);

        let nb5 = cfg.widgets.iter().find(|w| w.id == "out.notebook-5").expect("out.notebook-5");
        assert_eq!(nb5.role, WidgetRole::Output);
        assert_eq!(nb5.type_tag, "notebook");
        assert_eq!(nb5.props["container_id"], 5);
        assert!(!nb5.builtin);

        // N=3 → wf.note-3 + out.notebook-9.
        let w3 = cfg.workflows.iter().find(|w| w.id == "wf.note-3").expect("wf.note-3");
        assert_eq!(w3.outputs, vec!["out.notebook-9".to_string()]);
        assert!(cfg.widgets.iter().any(|w| w.id == "out.notebook-9"));

        // N=2 unbound → no workflow, no widget.
        assert!(!cfg.workflows.iter().any(|w| w.id == "wf.note-2"));
    }

    // ── Rule 4: listen voice override ───────────────────────────────────────

    #[test]
    fn listen_voice_settings_land_in_out_speak_override() {
        let mut cfg = AppConfig {
            listen_mode: "listen".into(),
            listen_voice_profile: "prof-1".into(),
            listen_voice: "am_echo".into(),
            ..Default::default()
        };
        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        let sp = cfg.widgets.iter().find(|w| w.id == "out.speak").expect("out.speak override");
        assert_eq!(sp.type_tag, "speak");
        assert_eq!(sp.props["voice_profile"], "prof-1");
        assert_eq!(sp.props["voice"], "am_echo");

        let l = cfg.workflows.iter().find(|w| w.id == "wf.listen").unwrap();
        assert_eq!(l.processors, vec!["llm.listen".to_string()]);
        assert_eq!(l.outputs, vec!["out.speak".to_string()]);
    }

    // ── Rule 5: text actions → workflows, five target mapping, cleared ──────

    #[test]
    fn text_actions_map_to_workflows_with_target_outputs_and_clear() {
        let mut cfg = AppConfig::default();
        cfg.text_actions = vec![
            TextActionBinding { hotkey: "cmd+1".into(), mode_id: "polish".into(), output_target: OutputTarget::FloatingPopup },
            TextActionBinding { hotkey: "cmd+2".into(), mode_id: "formal".into(), output_target: OutputTarget::ActiveTextField },
            TextActionBinding { hotkey: "cmd+3".into(), mode_id: "translate".into(), output_target: OutputTarget::Clipboard },
            TextActionBinding { hotkey: "cmd+4".into(), mode_id: "summarize".into(), output_target: OutputTarget::AppendToContainer },
            TextActionBinding { hotkey: "cmd+5".into(), mode_id: "polish".into(), output_target: OutputTarget::None },
        ];

        assert!(migrate_to_workflows(&mut cfg, &BTreeMap::new()));

        let ta = |i: usize| -> &WorkflowDef {
            cfg.workflows
                .iter()
                .find(|w| w.id == format!("wf.ta-{i}"))
                .unwrap_or_else(|| panic!("wf.ta-{i} missing"))
        };

        // index 0: floating_popup → out.panel.
        let t0 = ta(0);
        assert_eq!(t0.hotkey, "cmd+1");
        assert_eq!(t0.source, "src.selection");
        assert_eq!(t0.processors, vec!["llm.polish".to_string()]);
        assert_eq!(t0.outputs, vec!["out.panel".to_string()]);
        assert_eq!(t0.name, "文本动作 Polish");
        assert!(!t0.builtin);

        // The full five-target mapping.
        assert_eq!(ta(1).outputs, vec!["out.insert".to_string()], "active_text_field → out.insert");
        assert_eq!(ta(2).outputs, vec!["out.clipboard".to_string()], "clipboard → out.clipboard");
        assert_eq!(ta(3).outputs, vec!["out.quicknote".to_string()], "append_to_container → out.quicknote");
        assert_eq!(ta(4).outputs, vec!["out.clipboard".to_string()], "none → out.clipboard");

        // Processor ids and hotkeys carried through.
        assert_eq!(ta(1).processors, vec!["llm.formal".to_string()]);
        assert_eq!(ta(2).processors, vec!["llm.translate".to_string()]);
        assert_eq!(ta(3).processors, vec!["llm.summarize".to_string()]);
        assert_eq!(ta(4).hotkey, "cmd+5");

        // Legacy text_actions are cleared to prevent double-registration.
        assert!(cfg.text_actions.is_empty());
    }

    #[test]
    fn text_action_name_uses_custom_mode_display_name() {
        let mut custom = BTreeMap::new();
        custom.insert("mine".to_string(), llm_mode("我的模式"));
        let mut cfg = AppConfig::default();
        cfg.text_actions = vec![TextActionBinding {
            hotkey: "cmd+9".into(),
            mode_id: "mine".into(),
            output_target: OutputTarget::FloatingPopup,
        }];

        assert!(migrate_to_workflows(&mut cfg, &custom));
        let t0 = cfg.workflows.iter().find(|w| w.id == "wf.ta-0").unwrap();
        assert_eq!(t0.name, "文本动作 我的模式");
        assert_eq!(t0.processors, vec!["llm.mine".to_string()]);
    }

    // ── Coherence: no migrated workflow references a non-existent widget ────

    #[test]
    fn migrated_config_has_no_dangling_widget_references() {
        use crate::workflow::engine::{effective_widgets, effective_workflows};

        // A config exercising every rule at once.
        let mut custom = BTreeMap::new();
        custom.insert("mine".to_string(), llm_mode("Mine"));
        let mut cfg = AppConfig {
            dictation_mode: "mine".into(), // custom LLM dictation step
            hotkey_dictation_toggle: "cmd+shift+d".into(),
            notebook_hotkey_1: 5,
            notebook_hotkey_2: 7,
            listen_mode: "listen".into(),
            listen_voice_profile: "p".into(),
            listen_voice: "v".into(),
            ..Default::default()
        };
        cfg.text_actions = vec![
            TextActionBinding { hotkey: "cmd+1".into(), mode_id: "translate".into(), output_target: OutputTarget::FloatingPopup },
            TextActionBinding { hotkey: "cmd+2".into(), mode_id: "mine".into(), output_target: OutputTarget::AppendToContainer },
        ];

        assert!(migrate_to_workflows(&mut cfg, &custom));

        // Every effective workflow's source/processors/outputs must resolve to
        // a widget in the effective widget set (built-ins overlaid by config).
        let widget_ids: std::collections::HashSet<String> =
            effective_widgets(&cfg).into_iter().map(|w| w.id).collect();
        for wf in effective_workflows(&cfg) {
            assert!(widget_ids.contains(&wf.source), "{}: source '{}' missing", wf.id, wf.source);
            for p in &wf.processors {
                assert!(widget_ids.contains(p), "{}: processor '{p}' missing", wf.id);
            }
            for o in &wf.outputs {
                assert!(widget_ids.contains(o), "{}: output '{o}' missing", wf.id);
            }
        }
    }
}
