//! Agent processor — orchestrates the planner → executor → responder loop.
//!
//! [`AgentProcessor`] is the core runtime for the Fonos agent.  For each user
//! input it:
//!
//! 1. Checks the [`FastPathMatcher`] — simple patterns are dispatched directly
//!    to the skill executor without an LLM round-trip.
//! 2. **Planner** — builds an OpenAI-style chat-completion request that
//!    includes the full conversation history, the system prompt, and the
//!    `tools` array generated by the [`SkillRegistry`].  The request is sent
//!    via the injected [`LlmCaller`].
//! 3. **Executor** — if the planner response contains `tool_calls`, each call
//!    is dispatched to [`SkillRegistry::execute`] inside a
//!    [`tokio::time::timeout`] guard.
//! 4. **Responder** — assembles the final [`AgentResult`] and updates the
//!    [`ConversationContext`] so that future calls have access to the full
//!    dialogue history.
//!
//! # Testing without a real LLM
//!
//! The processor accepts any value that implements the [`LlmCaller`] trait,
//! making it straightforward to inject a mock during unit testing.  The
//! production helper [`HttpLlmCaller`] wraps the real
//! [`crate::llm::call_openai_compatible`] / [`crate::llm::call_anthropic`]
//! functions.

use std::pin::Pin;

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use super::{
    context::{ConversationContext, ToolCall},
    fast_path::{FastPathMatcher, FastPathResult},
    registry::SkillRegistry,
};
use crate::llm::ServiceConfig;

// ─── Public data types ────────────────────────────────────────────────────────

/// A record of a single skill invocation that occurred during agent processing.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SkillExecution {
    /// The name of the skill that was called.
    pub skill_name: String,
    /// The JSON parameters that were passed to the skill.
    pub params: Value,
    /// The text output returned by the skill (or an error message).
    pub output: String,
    /// Wall-clock duration of the execution in milliseconds.
    pub latency_ms: u64,
    /// `true` when the skill was blocked by the safety filter or was disabled.
    pub blocked: bool,
}

/// The complete result returned by [`AgentProcessor::process`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResult {
    /// The final natural-language response to show to the user.
    pub response_text: String,
    /// All skill executions that occurred while producing this result.
    pub skill_executions: Vec<SkillExecution>,
}

// ─── LlmCaller trait ─────────────────────────────────────────────────────────

/// An abstraction over the LLM HTTP call, used to enable testing without
/// real network access.
///
/// The trait is object-safe; callers may store it as `Box<dyn LlmCaller>` or
/// pass it as a generic parameter.
pub trait LlmCaller: Send + Sync {
    /// Send a chat-completion request and return the raw JSON response body.
    ///
    /// The returned JSON is expected to follow the OpenAI response schema so
    /// that [`AgentProcessor`] can extract `choices[0].message`.
    ///
    /// # Arguments
    ///
    /// * `service` — provider / model / key settings.
    /// * `messages` — the full conversation history as OpenAI-style objects.
    /// * `tools` — the `tools` array to include in the request (may be empty).
    fn call<'a>(
        &'a self,
        service: &'a ServiceConfig,
        messages: Vec<Value>,
        tools: Vec<Value>,
    ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<Value>> + Send + 'a>>;
}

// ─── Production LlmCaller ────────────────────────────────────────────────────

/// Production implementation of [`LlmCaller`] that calls the real provider APIs.
///
/// Routes to [`crate::llm::call_anthropic`] when `service.provider == "anthropic"`,
/// otherwise uses [`crate::llm::call_openai_compatible`].
pub struct HttpLlmCaller;

impl LlmCaller for HttpLlmCaller {
    fn call<'a>(
        &'a self,
        service: &'a ServiceConfig,
        messages: Vec<Value>,
        tools: Vec<Value>,
    ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<Value>> + Send + 'a>> {
        Box::pin(async move {
            if service.provider == "anthropic" {
                // Anthropic does not support tool-use via this path yet; fall
                // through to plain text response.
                let resp = crate::llm::call_anthropic(
                    &service.api_key,
                    &service.model,
                    &messages,
                    0.7,
                    1024,
                )
                .await?;
                Ok(json!({
                    "choices": [{
                        "message": {
                            "content": resp.text,
                            "tool_calls": null
                        }
                    }]
                }))
            } else {
                // Build the request body with tools.
                let url = if service.base_url.is_empty() {
                    "https://api.openai.com/v1/chat/completions".to_string()
                } else {
                    let base = service.base_url.trim_end_matches('/');
                    if base.ends_with("/v1") {
                        format!("{}/chat/completions", base)
                    } else {
                        format!("{}/v1/chat/completions", base)
                    }
                };

                let mut body = json!({
                    "model": service.model,
                    "messages": messages,
                    "temperature": 0.7,
                    "max_tokens": 256,
                });

                if !tools.is_empty() {
                    body["tools"] = json!(tools);
                }

                let client = reqwest::Client::builder()
                    .timeout(std::time::Duration::from_secs(60))
                    .build()
                    .map_err(|e| crate::Error::Http(e.to_string()))?;

                let mut req = client.post(&url).json(&body);
                if !service.api_key.is_empty() {
                    req = req.header(
                        "Authorization",
                        format!("Bearer {}", service.api_key),
                    );
                }

                let resp = req
                    .send()
                    .await
                    .map_err(|e| crate::Error::Llm(format!("LLM request failed: {e}")))?;

                if !resp.status().is_success() {
                    let status = resp.status();
                    let body_text = resp.text().await.unwrap_or_default();
                    return Err(crate::Error::Llm(format!(
                        "LLM API error {}: {}",
                        status,
                        body_text.chars().take(200).collect::<String>()
                    )));
                }

                let json_resp: Value = resp
                    .json()
                    .await
                    .map_err(|e| crate::Error::Llm(format!("parse error: {e}")))?;

                Ok(json_resp)
            }
        })
    }
}

// ─── AgentProcessor ──────────────────────────────────────────────────────────

/// Orchestrates the agent reasoning loop for a single session.
///
/// Hold one `AgentProcessor` per active agent session.  It owns the skill
/// registry, conversation context, and fast-path matcher for that session.
///
/// Call [`AgentProcessor::process`] for each user utterance.  The processor
/// is designed to work with any [`LlmCaller`] implementation so that the
/// planner step can be tested without network access.
pub struct AgentProcessor<C: LlmCaller = HttpLlmCaller> {
    /// All registered skills available for execution.
    registry: SkillRegistry,
    /// Rolling conversation history for this session.
    context: ConversationContext,
    /// Pattern-based pre-filter that bypasses the LLM for simple commands.
    fast_path: FastPathMatcher,
    /// System prompt sent as the first message of every LLM request.
    system_prompt: String,
    /// Maximum time (in seconds) allowed for a single skill execution.
    timeout_secs: u64,
    /// LLM caller implementation (real HTTP or mock in tests).
    llm_caller: C,
}

impl AgentProcessor<HttpLlmCaller> {
    /// Create a new [`AgentProcessor`] with the production HTTP LLM caller.
    ///
    /// # Arguments
    ///
    /// * `registry` — populated skill registry.
    /// * `context` — conversation context (may be pre-populated for session
    ///   resumption).
    /// * `fast_path` — configured fast-path matcher.
    /// * `system_prompt` — system prompt injected into every LLM request.
    /// * `timeout_secs` — execution timeout for skills in seconds.
    pub fn new(
        registry: SkillRegistry,
        context: ConversationContext,
        fast_path: FastPathMatcher,
        system_prompt: impl Into<String>,
        timeout_secs: u64,
    ) -> Self {
        Self {
            registry,
            context,
            fast_path,
            system_prompt: system_prompt.into(),
            timeout_secs,
            llm_caller: HttpLlmCaller,
        }
    }
}

impl<C: LlmCaller> AgentProcessor<C> {
    /// Create a new [`AgentProcessor`] with a custom [`LlmCaller`].
    ///
    /// Primarily intended for testing.
    pub fn with_caller(
        registry: SkillRegistry,
        context: ConversationContext,
        fast_path: FastPathMatcher,
        system_prompt: impl Into<String>,
        timeout_secs: u64,
        llm_caller: C,
    ) -> Self {
        Self {
            registry,
            context,
            fast_path,
            system_prompt: system_prompt.into(),
            timeout_secs,
            llm_caller,
        }
    }

    /// Process a user utterance and return the agent's result.
    ///
    /// # Steps
    ///
    /// 1. Check the fast-path matcher; if a pattern fires, skip the LLM.
    /// 2. Build the messages array (system prompt + conversation history +
    ///    current user message) and include the tool definitions from the
    ///    skill registry.
    /// 3. Call the LLM and parse the response.
    /// 4. If the response contains `tool_calls`, execute each skill inside a
    ///    timeout guard and collect the results.
    /// 5. Update the conversation context with all new messages and the final
    ///    response text.
    /// 6. Return an [`AgentResult`] with the response text and execution log.
    ///
    /// # Errors
    ///
    /// Returns an error if the LLM call fails and no fast-path matched.
    pub async fn process(
        &mut self,
        text: &str,
        llm_service: &ServiceConfig,
    ) -> crate::Result<AgentResult> {
        // ── Step 1: fast-path check ──────────────────────────────────────
        if let FastPathResult::Skill { skill_name, params } = self.fast_path.match_input(text) {
            return self
                .execute_skill_directly(text, &skill_name, params)
                .await;
        }

        // ── Step 2: build planner messages ───────────────────────────────
        let mut messages: Vec<Value> = Vec::new();

        // System prompt first (if non-empty).
        if !self.system_prompt.is_empty() {
            messages.push(json!({
                "role": "system",
                "content": self.system_prompt,
            }));
        }

        // Conversation history (prior turns).
        messages.extend(self.context.to_messages());

        // Current user message.
        messages.push(json!({
            "role": "user",
            "content": text,
        }));

        // Tool definitions from the registry.
        let tools = self.registry.tool_definitions();

        // ── Step 3: call LLM ─────────────────────────────────────────────
        let llm_response = self
            .llm_caller
            .call(llm_service, messages, tools)
            .await?;

        // ── Step 4: parse response and execute any tool calls ─────────────
        let message = &llm_response["choices"][0]["message"];
        let tool_calls_value = &message["tool_calls"];

        let (response_text, skill_executions) =
            if tool_calls_value.is_array() && !tool_calls_value.as_array().unwrap().is_empty() {
                self.handle_tool_calls(text, tool_calls_value).await?
            } else {
                // Plain text response — no skill execution.
                let content = message["content"]
                    .as_str()
                    .unwrap_or("")
                    .trim()
                    .to_string();

                // Update context with user message + plain assistant response.
                self.context.add_user_message(text);
                self.context.add_agent_response(&content);

                (content, Vec::new())
            };

        Ok(AgentResult {
            response_text,
            skill_executions,
        })
    }

    /// Return a read-only reference to the conversation context.
    pub fn context(&self) -> &ConversationContext {
        &self.context
    }

    /// Return a mutable reference to the conversation context.
    pub fn context_mut(&mut self) -> &mut ConversationContext {
        &mut self.context
    }

    /// Reset the conversation context.
    pub fn reset(&mut self) {
        self.context.reset();
    }

    /// Consume the processor and return its components for re-use.
    ///
    /// This is used by the Tauri command layer to return the registry,
    /// context, and fast-path matcher back to [`AgentState`] after each call.
    pub fn into_parts(self) -> (SkillRegistry, ConversationContext, FastPathMatcher) {
        (self.registry, self.context, self.fast_path)
    }

    // ── Private helpers ──────────────────────────────────────────────────────

    /// Execute a skill directly (fast-path bypass — no LLM call).
    async fn execute_skill_directly(
        &mut self,
        user_text: &str,
        skill_name: &str,
        params: Value,
    ) -> crate::Result<AgentResult> {
        let exec = self.run_skill(skill_name, params.clone()).await;
        let response_text = exec.output.clone();

        // Update context: record the user input and synthesise a simple
        // assistant response that reflects what the skill returned.
        self.context.add_user_message(user_text);
        self.context.add_agent_response(&response_text);

        Ok(AgentResult {
            response_text,
            skill_executions: vec![exec],
        })
    }

    /// Handle a `tool_calls` array from the LLM response.
    ///
    /// Each tool call is dispatched to the registry (with timeout).  After all
    /// tool results are collected, a summary response string is assembled from
    /// the outputs and the conversation context is updated.
    async fn handle_tool_calls(
        &mut self,
        user_text: &str,
        tool_calls_value: &Value,
    ) -> crate::Result<(String, Vec<SkillExecution>)> {
        let tool_calls_arr = tool_calls_value.as_array().unwrap();

        // Build ToolCall structs for the context.
        let tool_calls_for_context: Vec<ToolCall> = tool_calls_arr
            .iter()
            .map(|tc| ToolCall {
                id: tc["id"].as_str().unwrap_or("call_0").to_string(),
                function_name: tc["function"]["name"]
                    .as_str()
                    .unwrap_or("")
                    .to_string(),
                arguments: tc["function"]["arguments"]
                    .as_str()
                    .unwrap_or("{}")
                    .to_string(),
            })
            .collect();

        // Record user message and the assistant's tool-call request.
        self.context.add_user_message(user_text);
        for tc in &tool_calls_for_context {
            self.context.add_tool_call(tc.clone());
        }

        // Execute each skill and collect results.
        let mut skill_executions: Vec<SkillExecution> = Vec::new();
        let mut output_parts: Vec<String> = Vec::new();

        for (tc, ctx_tc) in tool_calls_arr.iter().zip(tool_calls_for_context.iter()) {
            let skill_name = tc["function"]["name"].as_str().unwrap_or("").to_string();
            let params: Value = tc["function"]["arguments"]
                .as_str()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or(Value::Object(serde_json::Map::new()));

            let exec = self.run_skill(&skill_name, params).await;

            // Record tool result in the context.
            self.context.add_tool_result(&ctx_tc.id, &exec.output);

            output_parts.push(exec.output.clone());
            skill_executions.push(exec);
        }

        // Assemble the final response text from all skill outputs.
        let response_text = output_parts.join("\n");

        // Record the final assistant response.
        self.context.add_agent_response(&response_text);

        Ok((response_text, skill_executions))
    }

    /// Run a single skill by name with the given params, respecting the
    /// configured timeout.  Always returns a [`SkillExecution`] — errors
    /// are captured in the `output` field rather than propagated.
    async fn run_skill(&self, skill_name: &str, params: Value) -> SkillExecution {
        let start = std::time::Instant::now();

        let timeout_duration = std::time::Duration::from_secs(self.timeout_secs);

        let result = tokio::time::timeout(
            timeout_duration,
            self.registry.execute(skill_name, params.clone()),
        )
        .await;

        let latency_ms = start.elapsed().as_millis() as u64;

        match result {
            Ok(Ok(skill_output)) => SkillExecution {
                skill_name: skill_name.to_string(),
                params,
                output: skill_output.output,
                latency_ms,
                blocked: false,
            },
            Ok(Err(e)) => {
                let msg = e.to_string();
                let blocked = msg.contains("disabled") || msg.contains("blocked");
                SkillExecution {
                    skill_name: skill_name.to_string(),
                    params,
                    output: format!("Error: {}", msg),
                    latency_ms,
                    blocked,
                }
            }
            Err(_elapsed) => SkillExecution {
                skill_name: skill_name.to_string(),
                params,
                output: format!(
                    "Error: skill '{}' timed out after {}s",
                    skill_name, self.timeout_secs
                ),
                latency_ms,
                blocked: false,
            },
        }
    }
}

// ─── Unit Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod test_agent_planner {
    //! Tests for INV-02: planner builds correct messages and parses LLM responses.

    use super::*;
    use crate::agent::{
        context::ConversationContext,
        fast_path::FastPathMatcher,
        registry::SkillRegistry,
        skill::{Skill, SkillOutput, SkillParam},
    };
    use crate::llm::ServiceConfig;
    use serde_json::json;
    use std::sync::{Arc, Mutex};

    // ── Mock LLM caller ──────────────────────────────────────────────────────

    /// Stores the last request payload and returns a pre-configured response.
    struct MockLlmCaller {
        /// The JSON value to return from every call.
        response: Value,
        /// Captures the messages sent on the most recent call.
        last_messages: Arc<Mutex<Vec<Value>>>,
        /// Captures the tools sent on the most recent call.
        last_tools: Arc<Mutex<Vec<Value>>>,
    }

    impl MockLlmCaller {
        /// Create a mock that returns a plain text response.
        fn plain_text(text: &str) -> Self {
            Self {
                response: json!({
                    "choices": [{
                        "message": {
                            "content": text,
                            "tool_calls": null
                        }
                    }]
                }),
                last_messages: Arc::new(Mutex::new(Vec::new())),
                last_tools: Arc::new(Mutex::new(Vec::new())),
            }
        }

        /// Create a mock that returns a tool-call response.
        fn tool_call(call_id: &str, function_name: &str, arguments: &str) -> Self {
            Self {
                response: json!({
                    "choices": [{
                        "message": {
                            "content": null,
                            "tool_calls": [{
                                "id": call_id,
                                "type": "function",
                                "function": {
                                    "name": function_name,
                                    "arguments": arguments
                                }
                            }]
                        }
                    }]
                }),
                last_messages: Arc::new(Mutex::new(Vec::new())),
                last_tools: Arc::new(Mutex::new(Vec::new())),
            }
        }

        /// Create a mock that returns an error.
        fn error(msg: &str) -> Self {
            let msg = msg.to_string();
            // We store a sentinel so we can detect the error path.
            // The actual error is produced in the `call` method by checking
            // if `response["error"]` is set.
            Self {
                response: json!({ "error": msg }),
                last_messages: Arc::new(Mutex::new(Vec::new())),
                last_tools: Arc::new(Mutex::new(Vec::new())),
            }
        }
    }

    impl LlmCaller for MockLlmCaller {
        fn call<'a>(
            &'a self,
            _service: &'a ServiceConfig,
            messages: Vec<Value>,
            tools: Vec<Value>,
        ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<Value>> + Send + 'a>> {
            *self.last_messages.lock().unwrap() = messages;
            *self.last_tools.lock().unwrap() = tools;

            let response = self.response.clone();

            Box::pin(async move {
                if response.get("error").is_some() {
                    let msg = response["error"].as_str().unwrap_or("mock error");
                    Err(crate::Error::Llm(msg.to_string()))
                } else {
                    Ok(response)
                }
            })
        }
    }

    // ── Mock skill ───────────────────────────────────────────────────────────

    /// A simple skill that echoes its `text` parameter.
    struct EchoSkill;

    impl Skill for EchoSkill {
        fn name(&self) -> &str {
            "echo"
        }
        fn description(&self) -> &str {
            "Echoes the supplied text back."
        }
        fn parameters(&self) -> Vec<SkillParam> {
            vec![SkillParam {
                name: "text".into(),
                description: "The text to echo.".into(),
                required: true,
                default: None,
            }]
        }
        fn execute(
            &self,
            params: Value,
        ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<SkillOutput>> + Send + '_>>
        {
            let text = params["text"].as_str().unwrap_or("").to_string();
            Box::pin(async move {
                Ok(SkillOutput {
                    output: text,
                    structured: None,
                })
            })
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    fn make_service() -> ServiceConfig {
        ServiceConfig {
            provider: "openai".into(),
            api_key: "test-key".into(),
            model: "gpt-4o".into(),
            base_url: String::new(),
        }
    }

    fn make_registry_with_echo() -> SkillRegistry {
        let mut reg = SkillRegistry::new();
        reg.register(Box::new(EchoSkill));
        reg
    }

    fn make_processor<C: LlmCaller>(caller: C) -> AgentProcessor<C> {
        AgentProcessor::with_caller(
            make_registry_with_echo(),
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "You are a helpful assistant.",
            30,
            caller,
        )
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    /// The planner includes the system prompt as the first message.
    #[tokio::test]
    async fn test_agent_planner_includes_system_prompt() {
        let caller = MockLlmCaller::plain_text("ok");
        let captured_messages = Arc::clone(&caller.last_messages);
        let mut proc = make_processor(caller);

        proc.process("hello", &make_service()).await.unwrap();

        let msgs = captured_messages.lock().unwrap();
        assert!(!msgs.is_empty(), "messages should not be empty");
        assert_eq!(msgs[0]["role"], "system");
        assert!(msgs[0]["content"]
            .as_str()
            .unwrap_or("")
            .contains("helpful assistant"));
    }

    /// The planner appends the user message after the system prompt.
    #[tokio::test]
    async fn test_agent_planner_includes_user_message() {
        let caller = MockLlmCaller::plain_text("ok");
        let captured_messages = Arc::clone(&caller.last_messages);
        let mut proc = make_processor(caller);

        proc.process("What is 2+2?", &make_service()).await.unwrap();

        let msgs = captured_messages.lock().unwrap();
        // Last message should be the user's input.
        let last = msgs.last().unwrap();
        assert_eq!(last["role"], "user");
        assert_eq!(last["content"], "What is 2+2?");
    }

    /// The planner includes the tool definitions for all enabled skills.
    #[tokio::test]
    async fn test_agent_planner_includes_tools() {
        let caller = MockLlmCaller::plain_text("ok");
        let captured_tools = Arc::clone(&caller.last_tools);
        let mut proc = make_processor(caller);

        proc.process("hello", &make_service()).await.unwrap();

        let tools = captured_tools.lock().unwrap();
        assert_eq!(tools.len(), 1, "one skill registered");
        assert_eq!(tools[0]["function"]["name"], "echo");
        assert_eq!(tools[0]["type"], "function");
    }

    /// When the conversation has prior history, it is included in the messages.
    #[tokio::test]
    async fn test_agent_planner_includes_conversation_history() {
        let caller = MockLlmCaller::plain_text("ok");
        let captured_messages = Arc::clone(&caller.last_messages);
        let mut proc = make_processor(caller);

        // Seed the context with a prior exchange.
        proc.context_mut().add_user_message("prior question");
        proc.context_mut().add_agent_response("prior answer");

        proc.process("follow-up question", &make_service())
            .await
            .unwrap();

        let msgs = captured_messages.lock().unwrap();
        // We expect: system, prior user, prior assistant, new user
        assert!(
            msgs.len() >= 4,
            "should include system + history + new user; got {} messages",
            msgs.len()
        );
        // The history messages appear after the system prompt.
        assert_eq!(msgs[1]["content"], "prior question");
        assert_eq!(msgs[2]["content"], "prior answer");
        assert_eq!(msgs[3]["content"], "follow-up question");
    }

    /// A plain-text LLM response is returned as response_text with no executions.
    #[tokio::test]
    async fn test_agent_planner_parses_plain_text_response() {
        let caller = MockLlmCaller::plain_text("The answer is 4.");
        let mut proc = make_processor(caller);

        let result = proc
            .process("What is 2+2?", &make_service())
            .await
            .unwrap();

        assert_eq!(result.response_text, "The answer is 4.");
        assert!(result.skill_executions.is_empty());
    }

    /// A tool-call response is correctly parsed: skill name and arguments extracted.
    #[tokio::test]
    async fn test_agent_planner_parses_tool_use_response() {
        let caller = MockLlmCaller::tool_call(
            "call_abc",
            "echo",
            r#"{"text": "hello from tool"}"#,
        );
        let mut proc = make_processor(caller);

        let result = proc
            .process("echo hello from tool", &make_service())
            .await
            .unwrap();

        assert_eq!(result.skill_executions.len(), 1);
        let exec = &result.skill_executions[0];
        assert_eq!(exec.skill_name, "echo");
        assert_eq!(result.response_text, "hello from tool");
    }

    /// An LLM error is returned as an Err — no panic.
    #[tokio::test]
    async fn test_agent_planner_handles_llm_error_gracefully() {
        let caller = MockLlmCaller::error("network timeout");
        let mut proc = make_processor(caller);

        let result = proc.process("anything", &make_service()).await;
        assert!(result.is_err(), "should propagate LLM error");
        let err = result.unwrap_err().to_string();
        assert!(err.contains("network timeout"));
    }

    /// After process() completes the conversation context contains the new exchange.
    #[tokio::test]
    async fn test_agent_planner_updates_context_after_plain_response() {
        let caller = MockLlmCaller::plain_text("Paris.");
        let mut proc = make_processor(caller);

        proc.process("Capital of France?", &make_service())
            .await
            .unwrap();

        let msgs = proc.context().messages();
        assert_eq!(msgs.len(), 2);
        assert_eq!(msgs[0].role, "user");
        assert_eq!(msgs[0].content, "Capital of France?");
        assert_eq!(msgs[1].role, "assistant");
        assert_eq!(msgs[1].content, "Paris.");
    }

    /// After a tool-call, the context contains the user message, tool-call
    /// assistant message, tool result, and final assistant response.
    #[tokio::test]
    async fn test_agent_planner_updates_context_after_tool_call() {
        let caller = MockLlmCaller::tool_call(
            "call_1",
            "echo",
            r#"{"text": "hi"}"#,
        );
        let mut proc = make_processor(caller);

        proc.process("say hi", &make_service()).await.unwrap();

        let msgs = proc.context().messages();
        // user → tool-call assistant → tool result → assistant summary
        assert!(msgs.len() >= 4, "context should have at least 4 messages");
        assert_eq!(msgs[0].role, "user");
        assert_eq!(msgs[0].content, "say hi");
    }

    /// Fast-path bypass: an "open Safari" input skips the LLM entirely.
    #[tokio::test]
    async fn test_agent_planner_fast_path_bypass_skips_llm() {
        // Register app_open skill.
        let mut reg = SkillRegistry::new();
        reg.register(Box::new(AppOpenSkill));

        // The MockLlmCaller will capture calls; we assert none are made.
        let caller = MockLlmCaller::plain_text("should not be called");
        let captured_messages = Arc::clone(&caller.last_messages);

        let mut proc = AgentProcessor::with_caller(
            reg,
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "system prompt",
            30,
            caller,
        );

        let result = proc
            .process("open Safari", &make_service())
            .await
            .unwrap();

        // LLM should NOT have been called.
        let msgs = captured_messages.lock().unwrap();
        assert!(msgs.is_empty(), "LLM should not be called for fast-path input");

        // But we should have a skill execution.
        assert_eq!(result.skill_executions.len(), 1);
        assert_eq!(result.skill_executions[0].skill_name, "app_open");
    }

    /// Helper skill for fast-path test.
    struct AppOpenSkill;

    impl Skill for AppOpenSkill {
        fn name(&self) -> &str {
            "app_open"
        }
        fn description(&self) -> &str {
            "Opens an application."
        }
        fn parameters(&self) -> Vec<SkillParam> {
            vec![SkillParam {
                name: "app".into(),
                description: "Application name.".into(),
                required: false,
                default: None,
            }]
        }
        fn execute(
            &self,
            params: Value,
        ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<SkillOutput>> + Send + '_>>
        {
            let app = params["app"].as_str().unwrap_or("").to_string();
            Box::pin(async move {
                Ok(SkillOutput {
                    output: format!("Opened {}", app),
                    structured: None,
                })
            })
        }
    }
}

#[cfg(test)]
mod test_agent_executor {
    //! Tests for INV-03: executor dispatches correctly, handles errors and timeout.

    use super::*;
    use crate::agent::{
        context::ConversationContext,
        fast_path::FastPathMatcher,
        registry::SkillRegistry,
        skill::{Skill, SkillOutput, SkillParam},
    };
    use crate::llm::ServiceConfig;
    use serde_json::json;
    use std::pin::Pin;

    // ── Fixed mock LLM caller ────────────────────────────────────────────────

    /// A mock that can be configured with different responses per call.
    struct FixedMockCaller {
        response: Value,
    }

    impl FixedMockCaller {
        fn tool_call(call_id: &str, function_name: &str, arguments: &str) -> Self {
            Self {
                response: json!({
                    "choices": [{
                        "message": {
                            "content": null,
                            "tool_calls": [{
                                "id": call_id,
                                "type": "function",
                                "function": {
                                    "name": function_name,
                                    "arguments": arguments
                                }
                            }]
                        }
                    }]
                }),
            }
        }
    }

    impl LlmCaller for FixedMockCaller {
        fn call<'a>(
            &'a self,
            _service: &'a ServiceConfig,
            _messages: Vec<Value>,
            _tools: Vec<Value>,
        ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<Value>> + Send + 'a>> {
            let response = self.response.clone();
            Box::pin(async move { Ok(response) })
        }
    }

    // ── Mock skills ──────────────────────────────────────────────────────────

    /// Echoes `params["text"]`.
    struct MockEchoSkill;

    impl Skill for MockEchoSkill {
        fn name(&self) -> &str {
            "mock_echo"
        }
        fn description(&self) -> &str {
            "Echoes text."
        }
        fn parameters(&self) -> Vec<SkillParam> {
            vec![SkillParam {
                name: "text".into(),
                description: "Text to echo.".into(),
                required: true,
                default: None,
            }]
        }
        fn execute(
            &self,
            params: Value,
        ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<SkillOutput>> + Send + '_>>
        {
            let text = params["text"].as_str().unwrap_or("").to_string();
            Box::pin(async move {
                Ok(SkillOutput {
                    output: text,
                    structured: None,
                })
            })
        }
    }

    /// A skill that always sleeps longer than any test timeout.
    struct SlowSkill;

    impl Skill for SlowSkill {
        fn name(&self) -> &str {
            "slow_skill"
        }
        fn description(&self) -> &str {
            "A skill that sleeps for a long time."
        }
        fn parameters(&self) -> Vec<SkillParam> {
            Vec::new()
        }
        fn execute(
            &self,
            _params: Value,
        ) -> Pin<Box<dyn std::future::Future<Output = crate::Result<SkillOutput>> + Send + '_>>
        {
            Box::pin(async move {
                tokio::time::sleep(std::time::Duration::from_secs(60)).await;
                Ok(SkillOutput {
                    output: "done".to_string(),
                    structured: None,
                })
            })
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    fn make_service() -> ServiceConfig {
        ServiceConfig {
            provider: "openai".into(),
            api_key: "test-key".into(),
            model: "gpt-4o".into(),
            base_url: String::new(),
        }
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    /// Executor dispatches to the correct skill and returns its output.
    ///
    /// Plan: skill="mock_echo", params={text: "hello"} → output "hello"
    #[tokio::test]
    async fn test_agent_executor_dispatches_echo_skill() {
        let mut reg = SkillRegistry::new();
        reg.register(Box::new(MockEchoSkill));

        let caller = FixedMockCaller::tool_call(
            "call_1",
            "mock_echo",
            r#"{"text": "hello"}"#,
        );

        let mut proc = AgentProcessor::with_caller(
            reg,
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "",
            30,
            caller,
        );

        let result = proc
            .process("say hello", &make_service())
            .await
            .unwrap();

        assert_eq!(result.skill_executions.len(), 1);
        let exec = &result.skill_executions[0];
        assert_eq!(exec.skill_name, "mock_echo");
        assert_eq!(exec.output, "hello");
        assert!(!exec.blocked);
        assert_eq!(result.response_text, "hello");
    }

    /// Executor handles an unknown skill name gracefully (error in output, not a panic).
    #[tokio::test]
    async fn test_agent_executor_unknown_skill_returns_error() {
        let reg = SkillRegistry::new(); // empty — no skills registered

        let caller = FixedMockCaller::tool_call(
            "call_1",
            "nonexistent_skill",
            r#"{}"#,
        );

        let mut proc = AgentProcessor::with_caller(
            reg,
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "",
            30,
            caller,
        );

        let result = proc.process("run it", &make_service()).await.unwrap();

        assert_eq!(result.skill_executions.len(), 1);
        let exec = &result.skill_executions[0];
        assert!(
            exec.output.contains("not found"),
            "output should mention 'not found', got: {}",
            exec.output
        );
    }

    /// Executor returns blocked=true when the skill is disabled.
    #[tokio::test]
    async fn test_agent_executor_disabled_skill_is_blocked() {
        let mut reg = SkillRegistry::new();
        reg.register(Box::new(MockEchoSkill));
        reg.toggle("mock_echo", false); // disable it

        let caller = FixedMockCaller::tool_call(
            "call_1",
            "mock_echo",
            r#"{"text": "hi"}"#,
        );

        let mut proc = AgentProcessor::with_caller(
            reg,
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "",
            30,
            caller,
        );

        let result = proc.process("try echo", &make_service()).await.unwrap();

        assert_eq!(result.skill_executions.len(), 1);
        let exec = &result.skill_executions[0];
        assert!(exec.blocked, "disabled skill should be marked as blocked");
        assert!(exec.output.contains("disabled"), "output should mention disabled");
    }

    /// A slow skill is timed out by the executor.
    ///
    /// Uses a 1-second timeout (not 5s) to keep the test fast.
    #[tokio::test]
    async fn test_agent_executor_timeout() {
        let mut reg = SkillRegistry::new();
        reg.register(Box::new(SlowSkill));

        let caller = FixedMockCaller::tool_call("call_1", "slow_skill", r#"{}"#);

        // Use a 1-second timeout so the test runs quickly.
        let mut proc = AgentProcessor::with_caller(
            reg,
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "",
            1, // 1 second timeout
            caller,
        );

        let result = proc
            .process("run slow skill", &make_service())
            .await
            .unwrap();

        assert_eq!(result.skill_executions.len(), 1);
        let exec = &result.skill_executions[0];
        assert!(
            exec.output.contains("timed out"),
            "output should mention timeout, got: {}",
            exec.output
        );
        // Latency should reflect the actual wait (around 1s).
        assert!(
            exec.latency_ms >= 900,
            "latency_ms should be >= 900, got {}",
            exec.latency_ms
        );
    }

    /// Executor correctly records latency_ms as a non-zero value.
    #[tokio::test]
    async fn test_agent_executor_records_latency() {
        let mut reg = SkillRegistry::new();
        reg.register(Box::new(MockEchoSkill));

        let caller = FixedMockCaller::tool_call(
            "call_1",
            "mock_echo",
            r#"{"text": "latency test"}"#,
        );

        let mut proc = AgentProcessor::with_caller(
            reg,
            ConversationContext::new(20),
            FastPathMatcher::new(),
            "",
            30,
            caller,
        );

        let result = proc.process("test latency", &make_service()).await.unwrap();
        let exec = &result.skill_executions[0];
        // latency_ms is always set (may be 0 on very fast machines, but the field exists).
        let _ = exec.latency_ms; // just verify it compiles and is accessible
    }

    /// AgentResult contains the correct fields (serialisation smoke test).
    #[test]
    fn test_agent_result_serialises() {
        let result = AgentResult {
            response_text: "hello".into(),
            skill_executions: vec![SkillExecution {
                skill_name: "echo".into(),
                params: json!({"text": "hello"}),
                output: "hello".into(),
                latency_ms: 42,
                blocked: false,
            }],
        };

        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains("response_text"));
        assert!(json.contains("skill_executions"));
        assert!(json.contains("latency_ms"));
        assert!(json.contains("blocked"));
    }
}
