//! LLM client — provider-agnostic text processing via OpenAI-compatible,
//! Anthropic, and Google Generative Language APIs.
//!
//! This module contains pure business logic with no platform dependency.
//! The platform command wrappers are responsible for reading application state,
//! resolving config, and recording stats; they delegate the actual API calls
//! to [`process_text`].

use crate::model_caps::ModelCaps;
use crate::modes::Mode;
use crate::{Error, Result};

/// Result returned from any LLM API call: the generated text and token usage.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LlmResponse {
    /// The text generated by the LLM (trimmed).
    pub text: String,
    /// Number of input (prompt) tokens consumed.
    pub tokens_in: i64,
    /// Number of output (completion) tokens generated.
    pub tokens_out: i64,
}

/// Minimal service configuration needed to make an LLM API call.
///
/// Callers (Tauri commands) extract these fields from the active model profile
/// stored in `AppConfig` and pass them here.
#[derive(Debug, Clone)]
pub struct ServiceConfig {
    /// Provider identifier: `"openai"`, `"anthropic"`, `"google"`, `"ollama"`, `"omlx"`, etc.
    pub provider: String,
    /// Bearer token or API key for the provider (may be empty for local providers).
    pub api_key: String,
    /// Model identifier to request (e.g. `"gpt-4o"`, `"claude-3-5-sonnet-20241022"`).
    pub model: String,
    /// Base URL override (empty string means use the provider default).
    pub base_url: String,
}

/// Process `text` through an LLM using the given `mode_def` and `service`.
///
/// Handles template substitution (`{text}`, `{target_lang}`), output language
/// enforcement, and capability-aware message construction before dispatching to
/// the correct provider API.
///
/// Returns `Ok(LlmResponse)` on success, or an [`Error::Llm`] describing what
/// went wrong.
///
/// # Arguments
///
/// * `text` — The input text to process (must not be empty).
/// * `mode_def` — The [`Mode`] definition that provides system prompt and user template.
/// * `service` — Connection parameters for the LLM provider.
/// * `caps` — Optional cached [`ModelCaps`]; `None` means the model has not been
///   probed yet (defaults to assuming system-prompt support).
/// * `translate_target` — The target language string from application config (used to
///   resolve `{target_lang}` in templates). Pass an empty string to default to `"English"`.
pub async fn process_text(
    text: &str,
    mode_def: &Mode,
    service: &ServiceConfig,
    caps: Option<&ModelCaps>,
    translate_target: &str,
) -> Result<LlmResponse> {
    let mut user_template_str = mode_def
        .user_template
        .as_deref()
        .ok_or_else(|| Error::Llm("Mode has no user_template".into()))?
        .to_string();

    // Substitute {target_lang} from config
    if user_template_str.contains("{target_lang}") {
        let target = if translate_target.is_empty() {
            "English"
        } else {
            translate_target
        };
        user_template_str = user_template_str.replace("{target_lang}", target);
    }

    // If output_language is set (not "auto"), append a language instruction
    let output_lang = &mode_def.output_language;
    if !output_lang.is_empty()
        && output_lang != "auto"
        && !user_template_str.contains("{target_lang}")
    {
        user_template_str = format!(
            "{}\n\nIMPORTANT: Output in {}.",
            user_template_str, output_lang
        );
    }

    // Build messages array adapted to model capabilities
    let messages = crate::model_caps::build_messages(
        text,
        mode_def.system.as_deref(),
        &user_template_str,
        caps,
    );

    let temperature = mode_def.temperature;

    let max_tokens = mode_def.max_tokens;

    match service.provider.as_str() {
        "anthropic" => call_anthropic(&service.api_key, &service.model, &messages, temperature, max_tokens).await,
        "google" => call_google(&service.api_key, &service.model, &messages, temperature, max_tokens).await,
        _ => {
            call_openai_compatible(
                &service.api_key,
                &service.model,
                &service.base_url,
                &messages,
                temperature,
                max_tokens,
                &service.provider,
            )
            .await
        }
    }
}

// ─── API callers ─────────────────────────────────────────────────────────────

/// Call an OpenAI-compatible chat completions endpoint.
///
/// Handles both the default `api.openai.com` endpoint and custom `base_url`
/// overrides (e.g. for Ollama or local MLX servers).
///
/// This function is public so that callers such as model-capability probing
/// can send arbitrary test messages directly without going through [`process_text`].
pub async fn call_openai_compatible(
    api_key: &str,
    model: &str,
    base_url: &str,
    messages: &[serde_json::Value],
    temperature: f64,
    max_tokens: u32,
    provider: &str,
) -> Result<LlmResponse> {
    let url = if base_url.is_empty() {
        "https://api.openai.com/v1/chat/completions".to_string()
    } else {
        let base = base_url.trim_end_matches('/');
        if base.ends_with("/v1") {
            format!("{}/chat/completions", base)
        } else {
            format!("{}/v1/chat/completions", base)
        }
    };

    // Adapt parameters per provider
    let is_openai = provider == "openai"
        || (base_url.is_empty() || base_url.contains("api.openai.com"));

    let mut body = serde_json::json!({
        "model": model,
        "messages": messages,
    });

    // Temperature: OpenAI reasoning models (o-series) and nano variants don't support it
    let skip_temperature = is_openai && {
        let m = model.to_lowercase();
        m.starts_with("o1") || m.starts_with("o3") || m.starts_with("o4")
            || m.contains("-nano")
    };
    if !skip_temperature {
        body["temperature"] = serde_json::json!(temperature);
    }

    // Max tokens: OpenAI uses max_completion_tokens; others use max_tokens
    if is_openai {
        body["max_completion_tokens"] = serde_json::json!(max_tokens);
    } else {
        body["max_tokens"] = serde_json::json!(max_tokens);
    }

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| Error::Http(e.to_string()))?;

    let mut req = client.post(&url).json(&body);
    if !api_key.is_empty() {
        req = req.header("Authorization", format!("Bearer {}", api_key));
    }

    let resp = req
        .send()
        .await
        .map_err(|e| Error::Llm(format!("LLM request failed: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(Error::Llm(format!(
            "LLM API error {}: {}",
            status,
            body.chars().take(200).collect::<String>()
        )));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Error::Llm(format!("parse error: {e}")))?;

    Ok(LlmResponse {
        text: json["choices"][0]["message"]["content"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string(),
        tokens_in: json["usage"]["prompt_tokens"].as_i64().unwrap_or(0),
        tokens_out: json["usage"]["completion_tokens"].as_i64().unwrap_or(0),
    })
}

/// Call the Anthropic Messages API.
///
/// Extracts any `"system"` role message from `messages` and sends it in the
/// dedicated `system` field required by the Anthropic API format.
///
/// This function is public so that callers such as model-capability probing
/// can send arbitrary test messages directly without going through [`process_text`].
pub async fn call_anthropic(
    api_key: &str,
    model: &str,
    messages: &[serde_json::Value],
    temperature: f64,
    max_tokens: u32,
) -> Result<LlmResponse> {
    // Extract system from messages (Anthropic uses a separate top-level field)
    let system = messages
        .iter()
        .find(|m| m["role"] == "system")
        .and_then(|m| m["content"].as_str())
        .unwrap_or("");
    let user_msgs: Vec<&serde_json::Value> = messages
        .iter()
        .filter(|m| m["role"] != "system")
        .collect();

    let body = serde_json::json!({
        "model": model,
        "max_tokens": max_tokens,
        "system": system,
        "messages": user_msgs,
        "temperature": temperature,
    });

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| Error::Http(e.to_string()))?;

    let resp = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", api_key)
        .header("anthropic-version", "2023-06-01")
        .json(&body)
        .send()
        .await
        .map_err(|e| Error::Llm(format!("Anthropic error: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(Error::Llm(format!(
            "Anthropic error {}: {}",
            status,
            body.chars().take(200).collect::<String>()
        )));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Error::Llm(format!("parse: {e}")))?;

    Ok(LlmResponse {
        text: json["content"][0]["text"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string(),
        tokens_in: json["usage"]["input_tokens"].as_i64().unwrap_or(0),
        tokens_out: json["usage"]["output_tokens"].as_i64().unwrap_or(0),
    })
}

/// Call the Google Generative Language API (Gemini).
///
/// Converts the OpenAI-style `messages` slice into Google's
/// `contents`/`system_instruction` format.
///
/// This function is public so that callers such as model-capability probing
/// can send arbitrary test messages directly without going through [`process_text`].
pub async fn call_google(
    api_key: &str,
    model: &str,
    messages: &[serde_json::Value],
    temperature: f64,
    max_tokens: u32,
) -> Result<LlmResponse> {
    let system = messages
        .iter()
        .find(|m| m["role"] == "system")
        .and_then(|m| m["content"].as_str())
        .unwrap_or("");
    let user_text = messages
        .iter()
        .find(|m| m["role"] == "user")
        .and_then(|m| m["content"].as_str())
        .unwrap_or("");

    let url = format!(
        "https://generativelanguage.googleapis.com/v1beta/models/{}:generateContent?key={}",
        model, api_key
    );
    let body = serde_json::json!({
        "system_instruction": {"parts": [{"text": system}]},
        "contents": [{"parts": [{"text": user_text}]}],
        "generationConfig": {"temperature": temperature, "maxOutputTokens": max_tokens},
    });

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| Error::Http(e.to_string()))?;

    let resp = client
        .post(&url)
        .json(&body)
        .send()
        .await
        .map_err(|e| Error::Llm(format!("Google error: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(Error::Llm(format!(
            "Google error {}: {}",
            status,
            body.chars().take(200).collect::<String>()
        )));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Error::Llm(format!("parse: {e}")))?;

    Ok(LlmResponse {
        text: json["candidates"][0]["content"]["parts"][0]["text"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string(),
        tokens_in: json["usageMetadata"]["promptTokenCount"]
            .as_i64()
            .unwrap_or(0),
        tokens_out: json["usageMetadata"]["candidatesTokenCount"]
            .as_i64()
            .unwrap_or(0),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_response_fields() {
        let r = LlmResponse {
            text: "hello".into(),
            tokens_in: 10,
            tokens_out: 5,
        };
        assert_eq!(r.text, "hello");
        assert_eq!(r.tokens_in, 10);
        assert_eq!(r.tokens_out, 5);
    }

    #[test]
    fn test_service_config_fields() {
        let s = ServiceConfig {
            provider: "openai".into(),
            api_key: "sk-test".into(),
            model: "gpt-4o".into(),
            base_url: String::new(),
        };
        assert_eq!(s.provider, "openai");
        assert_eq!(s.model, "gpt-4o");
    }
}
