//! LLM client — provider-agnostic text processing via OpenAI-compatible,
//! Anthropic, and Google Generative Language APIs.
//!
//! This module contains pure business logic with no platform dependency.
//! The platform command wrappers are responsible for reading application state,
//! resolving config, and recording stats; they delegate the actual API calls
//! to [`process_text`].

use crate::model_caps::ModelCaps;
use crate::{Error, Result};

/// Result returned from any LLM API call: the generated text and token usage.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LlmResponse {
    /// The text generated by the LLM (trimmed).
    pub text: String,
    /// Number of input (prompt) tokens consumed.
    pub tokens_in: i64,
    /// Number of output (completion) tokens generated.
    pub tokens_out: i64,
}

/// Minimal service configuration needed to make an LLM API call.
///
/// Callers (Tauri commands) extract these fields from the active model profile
/// stored in `AppConfig` and pass them here.
#[derive(Debug, Clone)]
pub struct ServiceConfig {
    /// Provider identifier: `"openai"`, `"anthropic"`, `"google"`, `"ollama"`, `"omlx"`, etc.
    pub provider: String,
    /// Bearer token or API key for the provider (may be empty for local providers).
    pub api_key: String,
    /// Model identifier to request (e.g. `"gpt-4o"`, `"claude-3-5-sonnet-20241022"`).
    pub model: String,
    /// Base URL override (empty string means use the provider default).
    pub base_url: String,
    /// STT API flavor for speech profiles: `"whisper"` (multipart upload,
    /// default) or `"chat"` (base64 audio in chat completions). Unused by
    /// LLM-only calls.
    pub stt_api: String,
}

/// Build the final user message: substitute `{target_lang}` from
/// `translate_target` (defaulting to `"English"` when empty), then — if
/// `output_language` is set and not `"auto"` — append an explicit
/// "IMPORTANT: Output in {output_language}." instruction. Split out of
/// [`process_text`] (Workbench P2 Task 14) so this pure string logic is
/// testable without a network mock; behavior is unchanged.
///
/// Quirk, documented rather than fixed here: the output-language append's
/// guard checks `template` for a literal `{target_lang}` *after* the
/// substitution above already ran, and `.replace()` removes every instance
/// of what it's asked to replace — so the guard is true whenever the
/// substitution just fired, not only when the template never had
/// `{target_lang}` to begin with. A template with both `{target_lang}` and a
/// non-`"auto"` `output_language` gets BOTH transformations, not one instead
/// of the other; see `build_user_message_applies_both_target_lang_and_output_language`.
fn build_user_message(template: &str, output_language: &str, translate_target: &str) -> String {
    let mut user_template_str = template.to_string();

    // Substitute {target_lang} from config
    if user_template_str.contains("{target_lang}") {
        let target = if translate_target.is_empty() {
            "English"
        } else {
            translate_target
        };
        user_template_str = user_template_str.replace("{target_lang}", target);
    }

    // If output_language is set (not "auto"), append a language instruction
    if !output_language.is_empty()
        && output_language != "auto"
        && !user_template_str.contains("{target_lang}")
    {
        user_template_str = format!(
            "{}\n\nIMPORTANT: Output in {}.",
            user_template_str, output_language
        );
    }

    user_template_str
}

/// Process `text` through an LLM using the given prompt configuration and `service`.
///
/// Handles template substitution (`{text}`, `{target_lang}`), output language
/// enforcement, and capability-aware message construction before dispatching to
/// the correct provider API.
///
/// Returns `Ok(LlmResponse)` on success, or an [`Error::Llm`] describing what
/// went wrong.
///
/// # Arguments
///
/// * `text` — The input text to process (must not be empty).
/// * `system` — Optional system prompt.
/// * `user_template` — User message template; must contain (or not) `{text}`/
///   `{target_lang}` placeholders as described below. `None` is an error — the
///   caller (e.g. [`crate::workflow::llm_step::run_llm_step`]) is expected to
///   default an unset template to `Some("{text}")` before calling in.
/// * `temperature` — LLM sampling temperature.
/// * `max_tokens` — Maximum tokens to request from the LLM.
/// * `output_language` — Desired output language; `"auto"` or empty preserves
///   the input language.
/// * `service` — Connection parameters for the LLM provider.
/// * `caps` — Optional cached [`ModelCaps`]; `None` means the model has not been
///   probed yet (defaults to assuming system-prompt support).
/// * `translate_target` — The target language string from application config (used to
///   resolve `{target_lang}` in templates). Pass an empty string to default to `"English"`.
#[allow(clippy::too_many_arguments)]
pub async fn process_text(
    text: &str,
    system: Option<&str>,
    user_template: Option<&str>,
    temperature: f64,
    max_tokens: u32,
    output_language: &str,
    service: &ServiceConfig,
    caps: Option<&ModelCaps>,
    translate_target: &str,
) -> Result<LlmResponse> {
    let user_template_str = build_user_message(
        user_template.ok_or_else(|| Error::Llm("no user_template".into()))?,
        output_language,
        translate_target,
    );

    // Build messages array adapted to model capabilities
    let messages = crate::model_caps::build_messages(
        text,
        system,
        &user_template_str,
        caps,
    );

    match service.provider.as_str() {
        "anthropic" => call_anthropic(&service.api_key, &service.model, &messages, temperature, max_tokens).await,
        "google" => call_google(&service.api_key, &service.model, &messages, temperature, max_tokens).await,
        _ => {
            call_openai_compatible(
                &service.api_key,
                &service.model,
                &service.base_url,
                &messages,
                temperature,
                max_tokens,
                &service.provider,
            )
            .await
        }
    }
}

/// Multi-turn chat completion: POST a prebuilt OpenAI-style messages array and
/// return the assistant content. Sibling to [`process_text`] (single-shot);
/// used by the Dialog session for follow-up turns.
///
/// Dispatches on `service.provider` exactly like `process_text` does, reusing
/// the same per-provider callers ([`call_anthropic`], [`call_google`],
/// [`call_openai_compatible`]) so the HTTP mechanics (endpoint resolution,
/// auth header, request shape, response parsing) stay identical to the
/// single-shot path. Errors are stringified for the simpler `Result<_, String>`
/// signature callers of `chat` expect.
pub async fn chat(
    service: &ServiceConfig,
    messages: Vec<serde_json::Value>,
    temperature: f64,
    max_tokens: u32,
) -> std::result::Result<String, String> {
    let result = match service.provider.as_str() {
        "anthropic" => {
            call_anthropic(&service.api_key, &service.model, &messages, temperature, max_tokens)
                .await
        }
        "google" => {
            call_google(&service.api_key, &service.model, &messages, temperature, max_tokens).await
        }
        _ => {
            call_openai_compatible(
                &service.api_key,
                &service.model,
                &service.base_url,
                &messages,
                temperature,
                max_tokens,
                &service.provider,
            )
            .await
        }
    };
    result.map(|r| r.text).map_err(|e| e.to_string())
}

// ─── API callers ─────────────────────────────────────────────────────────────

/// Resolve the chat-completions URL for an OpenAI-compatible endpoint: the
/// default `api.openai.com` when `base_url` is empty, otherwise the override
/// with `/v1/chat/completions` appended (or just `/chat/completions` when the
/// override already ends in `/v1`). Shared by [`call_openai_compatible`] and
/// the agent's [`crate::agent::processor::HttpLlmCaller`] so the two paths
/// can never drift.
pub(crate) fn openai_compatible_chat_url(base_url: &str) -> String {
    if base_url.is_empty() {
        return "https://api.openai.com/v1/chat/completions".to_string();
    }
    let base = base_url.trim_end_matches('/');
    if base.ends_with("/v1") {
        format!("{}/chat/completions", base)
    } else {
        format!("{}/v1/chat/completions", base)
    }
}

/// Resolve the chat-completions URL for **Google's OpenAI-compatibility
/// layer**, which lives under `/v1beta/openai/` — the `/v1/chat/completions`
/// shape [`openai_compatible_chat_url`] builds does not exist on
/// `generativelanguage.googleapis.com`. Used by the agent path, which needs
/// OpenAI-shaped tool calls; the plain-text path routes `google` to the
/// native [`call_google`] instead and never needs this.
pub(crate) fn google_openai_compat_chat_url(base_url: &str) -> String {
    let base = if base_url.is_empty() {
        "https://generativelanguage.googleapis.com"
    } else {
        base_url
    };
    let base = base.trim_end_matches('/');
    if base.ends_with("/v1beta/openai") {
        format!("{}/chat/completions", base)
    } else {
        format!("{}/v1beta/openai/chat/completions", base)
    }
}

/// Whether the target speaks OpenAI's parameter dialect — `api.openai.com`
/// rejects the deprecated `max_tokens` on current models and wants
/// `max_completion_tokens` instead, while most compatible servers (Ollama,
/// OpenRouter, Cerebras, Google's compat layer, …) still take `max_tokens`.
pub(crate) fn is_openai_param_dialect(provider: &str, base_url: &str) -> bool {
    provider == "openai" || base_url.is_empty() || base_url.contains("api.openai.com")
}

/// Call an OpenAI-compatible chat completions endpoint.
///
/// Handles both the default `api.openai.com` endpoint and custom `base_url`
/// overrides (e.g. for Ollama or local MLX servers).
///
/// This function is public so that callers such as model-capability probing
/// can send arbitrary test messages directly without going through [`process_text`].
pub async fn call_openai_compatible(
    api_key: &str,
    model: &str,
    base_url: &str,
    messages: &[serde_json::Value],
    temperature: f64,
    max_tokens: u32,
    provider: &str,
) -> Result<LlmResponse> {
    let url = openai_compatible_chat_url(base_url);

    // Adapt parameters per provider
    let is_openai = is_openai_param_dialect(provider, base_url);

    let mut body = serde_json::json!({
        "model": model,
        "messages": messages,
    });

    // Temperature: OpenAI reasoning models (o-series) and nano variants don't support it
    let skip_temperature = is_openai && {
        let m = model.to_lowercase();
        m.starts_with("o1") || m.starts_with("o3") || m.starts_with("o4")
            || m.contains("-nano")
    };
    if !skip_temperature {
        body["temperature"] = serde_json::json!(temperature);
    }

    // Max tokens: OpenAI uses max_completion_tokens; others use max_tokens
    if is_openai {
        body["max_completion_tokens"] = serde_json::json!(max_tokens);
    } else {
        body["max_tokens"] = serde_json::json!(max_tokens);
    }

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| Error::Http(e.to_string()))?;

    let mut req = client.post(&url).json(&body);
    if !api_key.is_empty() {
        req = req.header("Authorization", format!("Bearer {}", api_key));
    }

    let resp = req
        .send()
        .await
        .map_err(|e| Error::Llm(format!("LLM request failed: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(Error::Llm(format!(
            "LLM API error {}: {}",
            status,
            body.chars().take(200).collect::<String>()
        )));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Error::Llm(format!("parse error: {e}")))?;

    Ok(LlmResponse {
        text: json["choices"][0]["message"]["content"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string(),
        tokens_in: json["usage"]["prompt_tokens"].as_i64().unwrap_or(0),
        tokens_out: json["usage"]["completion_tokens"].as_i64().unwrap_or(0),
    })
}

/// Call the Anthropic Messages API.
///
/// Extracts any `"system"` role message from `messages` and sends it in the
/// dedicated `system` field required by the Anthropic API format.
///
/// This function is public so that callers such as model-capability probing
/// can send arbitrary test messages directly without going through [`process_text`].
pub async fn call_anthropic(
    api_key: &str,
    model: &str,
    messages: &[serde_json::Value],
    temperature: f64,
    max_tokens: u32,
) -> Result<LlmResponse> {
    // Extract system from messages (Anthropic uses a separate top-level field)
    let system = messages
        .iter()
        .find(|m| m["role"] == "system")
        .and_then(|m| m["content"].as_str())
        .unwrap_or("");
    let user_msgs: Vec<&serde_json::Value> = messages
        .iter()
        .filter(|m| m["role"] != "system")
        .collect();

    let body = serde_json::json!({
        "model": model,
        "max_tokens": max_tokens,
        "system": system,
        "messages": user_msgs,
        "temperature": temperature,
    });

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| Error::Http(e.to_string()))?;

    let resp = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", api_key)
        .header("anthropic-version", "2023-06-01")
        .json(&body)
        .send()
        .await
        .map_err(|e| Error::Llm(format!("Anthropic error: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(Error::Llm(format!(
            "Anthropic error {}: {}",
            status,
            body.chars().take(200).collect::<String>()
        )));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Error::Llm(format!("parse: {e}")))?;

    Ok(LlmResponse {
        text: json["content"][0]["text"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string(),
        tokens_in: json["usage"]["input_tokens"].as_i64().unwrap_or(0),
        tokens_out: json["usage"]["output_tokens"].as_i64().unwrap_or(0),
    })
}

/// Convert an OpenAI-style `messages` slice into Gemini's multi-turn `contents`
/// array, preserving order.
///
/// Maps every non-`"system"` message to `{"role": <mapped>, "parts": [{"text":
/// <content>}]}`, translating `"assistant"` → `"model"` (Gemini's term for the
/// model turn) and passing `"user"` through unchanged.
///
/// `"system"` messages are filtered out here, not translated. Gemini has a
/// separate `systemInstruction` field for that, but `call_google` does not
/// currently populate it from `messages` — see the note there. This is a
/// pure, side-effect-free function so it can be unit tested without any
/// network access.
fn google_contents_from_messages(messages: &[serde_json::Value]) -> Vec<serde_json::Value> {
    messages
        .iter()
        .filter(|m| m["role"] != "system")
        .map(|m| {
            let role = if m["role"] == "assistant" { "model" } else { "user" };
            let text = m["content"].as_str().unwrap_or("");
            serde_json::json!({"role": role, "parts": [{"text": text}]})
        })
        .collect()
}

/// Call the Google Generative Language API (Gemini).
///
/// Converts the OpenAI-style `messages` slice into Google's
/// `contents`/`system_instruction` format.
///
/// This function is public so that callers such as model-capability probing
/// can send arbitrary test messages directly without going through [`process_text`].
pub async fn call_google(
    api_key: &str,
    model: &str,
    messages: &[serde_json::Value],
    temperature: f64,
    max_tokens: u32,
) -> Result<LlmResponse> {
    // NOTE (pre-existing, out of scope here): `system` below is placed under
    // the JSON key `system_instruction` (snake_case), whereas every other key
    // in this request body (`generationConfig`, `maxOutputTokens`, ...) — and
    // Gemini's documented v1beta schema — use camelCase (`systemInstruction`).
    // That mismatch means the system prompt likely isn't actually honored by
    // the live API today, i.e. it is not reliably forwarded to Gemini. Left
    // unchanged here: we have no live Gemini credentials to verify a rename
    // is safe, and `process_text` (single-turn) already depends on this exact
    // shape. Tracked separately; `contents` (below) is the only thing this
    // fix changes.
    let system = messages
        .iter()
        .find(|m| m["role"] == "system")
        .and_then(|m| m["content"].as_str())
        .unwrap_or("");
    let contents = google_contents_from_messages(messages);

    let url = format!(
        "https://generativelanguage.googleapis.com/v1beta/models/{}:generateContent?key={}",
        model, api_key
    );
    let body = serde_json::json!({
        "system_instruction": {"parts": [{"text": system}]},
        "contents": contents,
        "generationConfig": {"temperature": temperature, "maxOutputTokens": max_tokens},
    });

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| Error::Http(e.to_string()))?;

    let resp = client
        .post(&url)
        .json(&body)
        .send()
        .await
        .map_err(|e| Error::Llm(format!("Google error: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(Error::Llm(format!(
            "Google error {}: {}",
            status,
            body.chars().take(200).collect::<String>()
        )));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Error::Llm(format!("parse: {e}")))?;

    Ok(LlmResponse {
        text: json["candidates"][0]["content"]["parts"][0]["text"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string(),
        tokens_in: json["usageMetadata"]["promptTokenCount"]
            .as_i64()
            .unwrap_or(0),
        tokens_out: json["usageMetadata"]["candidatesTokenCount"]
            .as_i64()
            .unwrap_or(0),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_response_fields() {
        let r = LlmResponse {
            text: "hello".into(),
            tokens_in: 10,
            tokens_out: 5,
        };
        assert_eq!(r.text, "hello");
        assert_eq!(r.tokens_in, 10);
        assert_eq!(r.tokens_out, 5);
    }

    #[test]
    fn test_service_config_fields() {
        let s = ServiceConfig {
            provider: "openai".into(),
            api_key: "sk-test".into(),
            model: "gpt-4o".into(),
            base_url: String::new(),
            stt_api: String::new(),
        };
        assert_eq!(s.provider, "openai");
        assert_eq!(s.model, "gpt-4o");
    }

    // ─── google_contents_from_messages (Gemini multi-turn conversion) ────────

    #[test]
    fn google_contents_single_user_message() {
        let messages = vec![serde_json::json!({"role": "user", "content": "hello"})];
        let contents = google_contents_from_messages(&messages);
        assert_eq!(contents.len(), 1);
        assert_eq!(contents[0]["role"], "user");
        assert_eq!(contents[0]["parts"][0]["text"], "hello");
    }

    #[test]
    fn google_contents_multi_turn_filters_system_and_preserves_order() {
        let messages = vec![
            serde_json::json!({"role": "system", "content": "sys prompt"}),
            serde_json::json!({"role": "user", "content": "first"}),
            serde_json::json!({"role": "assistant", "content": "reply"}),
            serde_json::json!({"role": "user", "content": "followup"}),
        ];
        let contents = google_contents_from_messages(&messages);
        assert_eq!(contents.len(), 3); // system filtered out
        assert_eq!(contents[0]["role"], "user");
        assert_eq!(contents[0]["parts"][0]["text"], "first");
        assert_eq!(contents[1]["role"], "model");
        assert_eq!(contents[1]["parts"][0]["text"], "reply");
        assert_eq!(contents[2]["role"], "user");
        assert_eq!(contents[2]["parts"][0]["text"], "followup");
    }

    #[test]
    fn google_contents_translates_assistant_role_to_model() {
        let messages = vec![serde_json::json!({"role": "assistant", "content": "hi there"})];
        let contents = google_contents_from_messages(&messages);
        assert_eq!(contents.len(), 1);
        assert_eq!(contents[0]["role"], "model");
        assert_eq!(contents[0]["parts"][0]["text"], "hi there");
    }

    // ─── build_user_message ({target_lang} + output_language substitution) ──

    #[test]
    fn build_user_message_leaves_template_untouched_with_no_placeholders_and_auto_output() {
        let out = build_user_message("Summarize: {text}", "auto", "");
        assert_eq!(out, "Summarize: {text}");
    }

    #[test]
    fn build_user_message_leaves_template_untouched_with_empty_output_language() {
        let out = build_user_message("Summarize: {text}", "", "French");
        assert_eq!(out, "Summarize: {text}");
    }

    #[test]
    fn build_user_message_substitutes_target_lang_from_translate_target() {
        let out = build_user_message("Translate to {target_lang}: {text}", "auto", "French");
        assert_eq!(out, "Translate to French: {text}");
    }

    #[test]
    fn build_user_message_substitutes_target_lang_defaulting_to_english_when_translate_target_empty() {
        let out = build_user_message("Translate to {target_lang}: {text}", "auto", "");
        assert_eq!(out, "Translate to English: {text}");
    }

    #[test]
    fn build_user_message_appends_output_language_instruction_when_set_and_not_auto() {
        let out = build_user_message("Summarize: {text}", "Spanish", "");
        assert_eq!(out, "Summarize: {text}\n\nIMPORTANT: Output in Spanish.");
    }

    #[test]
    fn build_user_message_applies_both_target_lang_and_output_language() {
        // Documented quirk (see build_user_message's doc comment): the
        // output_language append isn't skipped just because the template
        // originally had {target_lang} — its guard runs against the
        // already-substituted string, which no longer contains the literal
        // placeholder either way. Pinning this as current, real behavior.
        let out = build_user_message("Translate to {target_lang}: {text}", "Spanish", "French");
        assert_eq!(
            out,
            "Translate to French: {text}\n\nIMPORTANT: Output in Spanish."
        );
    }

    // ─── openai_compatible_chat_url ──────────────────────────────────────────

    #[test]
    fn openai_compatible_chat_url_defaults_to_api_openai_com_when_base_empty() {
        let url = openai_compatible_chat_url("");
        assert_eq!(url, "https://api.openai.com/v1/chat/completions");
    }

    #[test]
    fn openai_compatible_chat_url_appends_only_chat_completions_when_base_ends_in_v1() {
        let url = openai_compatible_chat_url("https://api.cerebras.ai/v1");
        assert_eq!(url, "https://api.cerebras.ai/v1/chat/completions");
    }

    #[test]
    fn openai_compatible_chat_url_trims_trailing_slash_before_checking_v1_suffix() {
        let url = openai_compatible_chat_url("https://api.cerebras.ai/v1/");
        assert_eq!(url, "https://api.cerebras.ai/v1/chat/completions");
    }

    #[test]
    fn openai_compatible_chat_url_appends_v1_chat_completions_when_base_has_no_v1_suffix() {
        let url = openai_compatible_chat_url("https://example.com/");
        assert_eq!(url, "https://example.com/v1/chat/completions");
    }

    // ─── google_openai_compat_chat_url ───────────────────────────────────────

    #[test]
    fn google_openai_compat_chat_url_defaults_to_generativelanguage_googleapis_com_when_base_empty(
    ) {
        let url = google_openai_compat_chat_url("");
        assert_eq!(
            url,
            "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
        );
    }

    #[test]
    fn google_openai_compat_chat_url_appends_only_chat_completions_when_base_already_has_v1beta_openai_suffix()
     {
        let url = google_openai_compat_chat_url("https://generativelanguage.googleapis.com/v1beta/openai");
        assert_eq!(
            url,
            "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
        );
    }

    #[test]
    fn google_openai_compat_chat_url_appends_full_path_for_bare_preset_base() {
        let url = google_openai_compat_chat_url("https://generativelanguage.googleapis.com");
        assert_eq!(
            url,
            "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
        );
    }

    // ─── is_openai_param_dialect ─────────────────────────────────────────────

    #[test]
    fn is_openai_param_dialect_true_for_openai_provider_regardless_of_base_url() {
        assert!(is_openai_param_dialect("openai", "https://some-proxy.example.com"));
    }

    #[test]
    fn is_openai_param_dialect_false_for_openrouter() {
        assert!(!is_openai_param_dialect(
            "openrouter",
            "https://openrouter.ai/api/v1"
        ));
    }

    #[test]
    fn is_openai_param_dialect_true_for_empty_base_url_since_it_means_api_openai_com() {
        assert!(is_openai_param_dialect("custom", ""));
    }

    #[test]
    fn is_openai_param_dialect_false_for_cerebras() {
        assert!(!is_openai_param_dialect(
            "cerebras",
            "https://api.cerebras.ai/v1"
        ));
    }
}
